### ISSUE TITLE
SEGFAULT on Linux

### ISSUE THREAD

**Issue by stramel** [atom/tabs#104]
**OS:** Ubuntu 14.04
**Atom:** 0.167.0-8f4555b
**tabs:** 0.61.0

#### Steps to Reproduce

1. Open Atom with `--safe`
2. File > Open Folder...
3. Select a project
4. Open two files
5. Right-click a tab
6. Select 'Close All Tabs' or 'Reveal in Tree View'

Here is the crash dump from `--safe` mode: http://pastebin.com/1ndyvXRC

Seems to be issue with Atom on Linux, atom/atom#4892, atom/tree-view#310

**Comment by lee-dohm** [comment]
Closing this in favor of the main issue atom/atom#4892 since they're all related.
