### ISSUE TITLE
Suggestion: Hide tab bar when only 1 tab is open

### ISSUE THREAD

**Issue by modest** [atom/tabs#109]
Would be a nice config option, at least.  This follows the behavior of many other tabbed Mac apps such as Safari.

![screen shot 2015-01-24 at 3 30 04 pm](https://cloud.githubusercontent.com/assets/990299/5889467/feea1cc4-a3dd-11e4-93b4-a67a9d375b62.png)
![screen shot 2015-01-24 at 3 30 24 pm](https://cloud.githubusercontent.com/assets/990299/5889468/0200318c-a3de-11e4-8535-57abf33e2ac0.png)

**Comment by simurai** [comment]
@modest Are you thinking of changing this behaviour for all themes? Or just the one in your screenshot, I believe it's Atom Light UI.

The [Unity UI](https://atom.io/themes/unity-ui) theme does it like that:

![screen shot 2015-01-25 at 10 48 01 am](https://cloud.githubusercontent.com/assets/378023/5889853/a95f842c-a47f-11e4-8ad3-5eacbe5426b2.png)

And maybe more. It's probably better to leave it up to the theme to decide.

**Comment by benogle** [comment]
Closing as this is a theme related issue. Unity ui does what you would like.

**Comment by modest** [comment]
Sorry, screenshot was misleading.  Replaced with the right before & after picture.  Unity is unrelated.

**Comment by benogle** [comment]
This is unlikely to be added to core. Maybe one could create a theme that hides the tab bar when there is only one tab.

**Comment by simurai** [comment]
hey, "there is a package for that™": https://atom.io/packages/one-tab

ps. had reload Atom after installing, but after it works fine

**Comment by modest** [comment]
Since this is fairly standard default behavior across tabbed apps (see: TextMate, Finder, Safari, Transmit), it might be reasonable to include this in the core tabs package, at least as a setting :)  Gave it my best shot.
