### ISSUE TITLE
Tabs not opening since 0.176.0

### ISSUE THREAD

**Issue by mesosteros** [atom/tabs#113]
My tabs collapse into one only. Only the settings menu shows in a different tab. 
If I disable and enable the package, all the tabs show but simply opening a new one collapses them again.

**Comment by verheyenkoen** [comment]
+1

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/debugging)? Also, could you give the following information?

* What OS and version are you running?
* Do you have the [Shadow DOM feature](http://blog.atom.io/2015/01/05/enable-shadow-dom.html) enabled?
* Do you have the [Emmet package](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by mesosteros** [comment]
Yes Lee.
OS is Windows 8.1 x64 bits, Xubuntu 14.10 and my colleague on a Mac Yosemite also has the same issue (I've checked)
The version is 0.176.0.
I have Shadow DOM enabled.
Emmet is NOT installed.
The behaviour doesn't seemed fixed on normal Atom so Atom --safe is not a surefire way of checking this (although I have yet to see one instance of it). 
Thing is: I installed no packages before this started happening. This was when the 0.176.0 update hit my Atom installs on Win and Linux (and my colleague's Mac).

**Comment by lee-dohm** [comment]
I can't reproduce what you're seeing on Atom v0.177.0-e7b790c on Mac OS X 10.10.1:

![screen shot 2015-01-29 at 9 40 00 am](https://cloud.githubusercontent.com/assets/1038121/5962738/d440f37e-a79a-11e4-9d85-12d8f30c2615.png)

I haven't tried on v0.176.0 specifically, but I'm on v0.64.0 of the tabs package and according to this:

https://github.com/atom/atom/blob/v0.176.0/package.json#L117

that's what v0.176.0 of Atom is using. So there must be some difference in configuration, etc.

**Comment by mesosteros** [comment]
You can close this for now I think... the behaviour magically disappeared all of a sudden... no updates no package disabling... Weird...

**Comment by lee-dohm** [comment]
Ok, thanks. Let us know if it reproduces :grinning:
