### ISSUE TITLE
Tooltips take too long to pop up

### ISSUE THREAD

**Issue by ricardograca** [atom/tabs#117]
This is probably personal opinion, but to me the tooltips that display the complete path name of a file take too long to appear.

Compared to every other tooltip I can think of in my system it takes at least twice as much for the ones on Atom tabs to show up. This can be really annoying if I have several files with the same name open at the same time (`index.js` comes to mind). They seem to be taking something like 2+ seconds to show up, where as all other tooltips I tested appeared between 500ms to 1s.

Even worse, is that if I jump from tab to tab, it takes another 2+ seconds for the next tooltip to appear. Usually I would expect the next tooltip to show up immediately if I move the cursor through the various tabs.

**Comment by simurai** [comment]
The delay is now changed from `2s` to `1s`.

> Usually I would expect the next tooltip to show up immediately if I move the cursor through the various tabs.

I like this suggestion. Might be good to add it for all tooltips and not just for the tabs. I'll make a new issue in Core.

**Comment by ricardograca** [comment]
Many thanks :)

I was only talking about tabs in terms of tooltips appearing immediately, but it may work for other elements as well. I never thought of that actually.
