### ISSUE TITLE
Switch tabs onMouseDown

### ISSUE THREAD

**Issue by KeitIG** [atom/tabs#123]
Hello,

I was surprised to not find any issue on this. What about switch tabs onMouseDown() instead of Click() ? It has all benefits: you can see the tab sooner, the UI seems more reactive...

ref: https://github.com/atom/atom/issues/5174

As as-cii mentioned, it is not really "pure performance improvement". Just a (working) trick.

I guess I could do a PR myself, but what do you think about that ?

**Comment by swinbank** [comment]
I do agree that perceived responsiveness is important. I tinkered with this about a year ago, but I vaguely remember it being slightly more trivial than I had bargained for, since it was affecting the ability to drag tabs around.

**Comment by KeitIG** [comment]
@swinbank take a look at my PR. I've fixed it ;)

**Comment by swinbank** [comment]
Great!

**Comment by 50Wliu** [comment]
This has been merged so closing.
