### ISSUE TITLE
Tab resize should be delayed

### ISSUE THREAD

**Issue by izuzak** [atom/tabs#129]
_From @karai17 on April 7, 2015 17:2_

If I have a lot of tabs open and I want to close several of them, it can be a little annoying to have to continue adjusting the mouse when I am trying to close tabs as they resize. Chrome does a good job at this: When you close a tab, the other tabs shift to fill the space but they do not resize to fill space for a second or two, giving you the ability to close several tabs in a row quickly without having to move your mouse.

_Copied from original issue: atom/atom#6287_

**Comment by izuzak** [comment]
_From @mnquintana on April 7, 2015 23:41_

:+1: I really like this idea!

**Comment by izuzak** [comment]
_From @philipgiuliani on April 8, 2015 11:19_

Chrome isn't delaying the tab-resize, they are doing it as soon as you remove the mouse from the tabbar. I also would like to see this nice feature :)

For now, just use `CMD + W`.

**Update**
I just looked over this, and the main problem is, that the tab-resize is handled with CSS (flex), so its currently not easliy possible to implement this feature.

This issue should go to the following repo: https://github.com/atom/tabs

**Comment by karai17** [comment]
Would it be possible to move the reflow styles to only activate on mouse leave?

**Comment by philipgiuliani** [comment]
@karai17 no i dont think this is possible. My idea would be to get the current tab-width with javascript on a mouseover and set it as a style. When the mouse leaves it should be removed again and the tabs will get bigger than. Maybe i could try that out :)

**Comment by karai17** [comment]
That sounds like it could work!

**Comment by philipgiuliani** [comment]
I just tried it out and was not very successful so far :/ The tabbar has `display: flex`, so its not possible to set a fixed-width to the tabs. I did a workaround to set the tab-width and remove display: flex from the tab-bar which worked, but not perfectly. The last tab disappears for some reason but i can look into it.

My current problem is that the active tab has another with than the current tab. Thats in Google Chrome not the case. So currently the delaying has no sense because you get interrupted by the active tab. And as soon as you close it the next tab gets active of course.

**Comment by karai17** [comment]
Any idea on how google manages it in chrome? If atom runs on top of WebKit
or blink, could we not snag chrome's tab system? I know of a project,
clover, that embeds windows explorer inside a chrome framework which is
quite novel and works mostly well.

**Comment by philipgiuliani** [comment]
That would mean that the tabbar is implemented nativly and has not the flexibility anymore that atom has (styling through CSS for example). If the active-tab would have the same width as the other tabs, it should work :)

**Comment by karai17** [comment]
While I do admire atom's attempt to be flexible, I feel like not every
single aspect needs to be quite so flexible. Building a chrome-like tab
system should be enough for most people to be happy. The few people who
just really want to customize tabs might just have to accept that.

**Comment by philipgiuliani** [comment]
Chrome-like tab system should be no problem, also with this flexibility :)

**Comment by karai17** [comment]
Perfect, I look forward to future updates!

**Comment by kobestarr** [comment]
I just spent ages seeing if this would work. Sounds like a great idea!

**Comment by erwan** [comment]
@philipgiuliani do you have a branch of the stuff you tried?

**Comment by philipgiuliani** [comment]
@erwan no sorry i just had it locally :( But it didn't work because the active tab had another size. with the current updated one-dark/light themes it should work. I think this functionality (at least how i thought to implement it) would break a lot of other themes.. I could try it now with all this updated stuff again!

**Comment by simurai** [comment]
> I think this functionality (at least how i thought to implement it) would break a lot of other themes..

Yeah, I can imagine it's tricky to do for all themes. And in the One theme there is already a discussion about having 2 tab size modes: https://github.com/atom/one-dark-ui/pull/94.

Moving the close button to left might help https://github.com/atom/one-dark-ui/pull/95? But I think it also depends on the theme.. some resize depending how much space is available. And that would be only on Mac.

**Comment by alexandernst** [comment]
Any news on this one?

**Comment by xiata** [comment]
Following is a hack that is pretty close to Chrome's tab closing behavior. That what you're talking about?

```javascript
!function() {
    var affected = [];
    var sizes = [];
    var tabBar = document.querySelector('.tab-bar[is="atom-tabs"]');

    tabBar.addEventListener('mouseenter', function() {
        var tabs = tabBar.querySelectorAll('.tab[is="tabs-tab"]');
        for (var len = tabs.length, i = 0; i < len; ++i) {
            var tab = tabs[i];
            if (affected.indexOf(tab) === -1) {
                affected[affected.length] = tab;
                sizes[sizes.length] = tab.style.maxWidth;
                tab.style.maxWidth = tab.offsetWidth + 'px';
            }
        }
    });

    tabBar.addEventListener('mouseleave', function() {
        while (affected.length) {
            affected.pop().style.maxWidth = sizes.pop();
        }
    });
}();
```

**Comment by simurai** [comment]
Haven't tested @xiata code, but here a gif of Chrome's behavior:

![tabs](https://cloud.githubusercontent.com/assets/378023/13306779/e40a34fc-dba9-11e5-84be-77e38d30802e.gif)

Notice that the tabs resize only __after__ leaving the tab bar. Quickly close tabs like this would only work if all tabs are the same size or if the close button is on the left. So it also depends on the theme.
