### ISSUE TITLE
Save file by dblclicking tab

### ISSUE THREAD

**Issue by skogshjort** [atom/tabs#131]
It would be wonderful to have the functionality to save the file of a tab by double clicking it.

I tested it by hacking it into the tabs package, and it's not that hard. As the tabs' appearance reflect changes to their files, interacting with them feels natural, and the difference in appearance worked as an indicator for the saving action imo. Disappeared with the next update though, obviously ;)

**Comment by thedaniel** [comment]
I like the idea of interacting directly with a tab but this seems too easy to do by accident for a potentially destructive action.

**Comment by thomasjo** [comment]
I'm :-1: on this one.

First of all this behavior is completely unexpected—I'm not aware of any mainstream editor that does this. Of course that shouldn't really prevent us from doing it in Atom, but that brings me to my second issue; I don't understand the reason to add this behavior. Why would I double click a tab, instead of pressing <kbd>cmd</kbd> + <kbd>s</kbd> or <kbd>ctrl</kbd> + <kbd>s</kbd> which is much quicker?

**Comment by mnquintana** [comment]
> As the tabs' appearance reflect changes to their files

This isn't true out of the box though – this is only true if you have something like [git-tab-status](https://atom.io/packages/git-tab-status) installed. Otherwise their appearance doesn't reflect any changes made to the files.

I'd also be :-1: for this - I think doing *something* on double click might be nice, but I'm not convinced it should be saving. This might up being even more confusing once #3683 ships.

**Comment by skogshjort** [comment]
> First of all this behavior is completely unexpected
> [...] their appearance doesn't reflect any changes made to the files.

Sorry for the vague explanation. I referred to the close button being replaced by a blue circle in both the One and Atom themes by default. It clearly signals *this tab is unsaved*.

![tab_unsaved](https://cloud.githubusercontent.com/assets/3176525/7337313/fdec0932-ec25-11e4-8992-e1da04a6ef6e.jpg)

> Why would I double click a tab [...]

Just because keyboard shortcuts exist doesn't mean mouse navigation is unnecessary. Say a person uses an OS primarily using the mouse. Saving the file right after writing some code is easy using the keyboard shortcut. Saving right after focusing the atom editor with the mouse requires (in a worst case scenario) to click the tab, move to the keyboard, use the shortcut, move back to the mouse in order to move on, in contrast to just double clicking the unsaved tab and directly move on. For most alt-tabbers this is a non-scenario, but on the other hand, why would they try to double click a tab? ;)

> [...] I think doing something on double click might be nice

I'm open for making this pr bigger. What if we had a drop down in the tabs package settings for choosing their preferable behavior, like saving, closing or pinning? It could then be defaulted to "no action" and complemented with a similar for middle click. :)

**Comment by thomasjo** [comment]
I'm for adding *Save* to the tab's context menu. That would solve the issue at hand, and it's a minimal change with much less problems than the proposed double-clicking scheme. For instance what if the user double-clicks the tab for a non-editor pane item (e.g. Markdown Preview)? Should we simply do nothing? If we go the context menu route, we would simply not list the *Save* option for non-file pane items (this type of differentiation is already supported at the tab-level).

**Comment by skogshjort** [comment]
@thomasjo But isn't the same is true for current functionality? What happens when pressing <kbd>cmd</kbd> + <kbd>S</kbd>  or <kbd>ctrl</kbd> + <kbd>S</kbd> for a non-editor pane item? Nothing?

**Comment by thomasjo** [comment]
@skogshjort Definitely, and that's a good point, although the difference is that it's
  1. existing behavior,
  2. both standard, and a discoverable shortcut/keybind via the *Edit* menu,
  3. explicit in such a way that it's unlikely to happen accidentally.

The proposed enhancement is neither discoverable outside of documentation (or digging into the configuration to find the (potentially implemented) list of double-click actions), nor is it explicit enough. For people who use a trackpad, it's not at all unlikely that they might accidentally double-click the tab. And if double-clicking saves, it might be, as @thedaniel pointed out, potentially destructive. That could be partially remedied with your proposed action list, but that adds more configuration options and makes the feature unlikely to discovered by the average user.

All in all, I don't see how this is worth the effort to implement, document and maintain, in light of all the drawbacks. As I mentioned earlier, I'm all for adding save actions to the tab's context menu. That's also two clicks, and if we place it high on the list will incur minimal mouse movement.

/cc @atom/non-github-maintainers

**Comment by skogshjort** [comment]
I see. If the ability to configure actions for double click can't make it into the tabs package, I guess I'll have to just make my own little package instead. 

> [...] but that adds more configuration options and makes the feature unlikely to discovered by the average user.

I understand why that is a bad thing, but since "Tab Scrolling" seemed to be worth the effort, I figured maybe double click functions would too. :)

**Comment by thomasjo** [comment]
> I guess I'll have to just make my own little package instead.

I'm sure you'll find people willing to help out with that—I don't doubt that some users will find the proposed feature useful, I'm mostly concerned with adding something that the majority of users might not even discovers exists.

Regardless, keep the suggestions rolling even though some of them might get a little bit of pushback :wink:

**Comment by skogshjort** [comment]
> Regardless, keep the suggestions rolling even though some of them might get a little bit of pushback

I will! :)
