### ISSUE TITLE
Editor not focused when switching tabs

### ISSUE THREAD

**Issue by Eschon** [atom/tabs#135]
When I switch tabs the editor doesn't get focus. According to #30 this should have been fixed already but it doesn't work for me.

OS: OS X 10.10.3
Atom Version: 0.198.0
Tabs Version: 0.68.0

**Comment by mnquintana** [comment]
Duplicate of https://github.com/atom/atom/issues/6662 - please subscribe there for updates.

**Comment by kaisellgren** [comment]
I had this same problem and it turned out it was the Settings -> Tree View -> Focus On Reveal option. Turning it off will keep the focus on the editor while switching tabs.
