### ISSUE TITLE
Option for auto-scroll when hidden.

### ISSUE THREAD

**Issue by v3ss0n** [atom/tabs#138]
Neeed an option for this:
- When tabs are hidden due to too many files  , automatically scroll to the latest , newly opened files.

**Comment by v3ss0n** [comment]
anyone interested in working on this?

**Comment by CadenP** [comment]
Focusing a tab that is already open (selecting a file either by using Fuzzy Finder or Project Find [`CMD+SHIFT+F`]) does not move the tab into view if it is off-screen (too many tabs).

STEPS:
1. Have too many tabs open - let them go off the screen.
2. Use Fuzzy Finder to go to a tab that is off screen.
3. Notice:
 - Tab content is focused
 - Tab itself is focused but still off-screen.

Desired behaviour:
Scroll row of tabs to make focused tab visible.

Actual behaviour:
Doesn't do that. (stays put)

**Comment by CadenP** [comment]
In addition:

`CMD+OPTION+ARROW` to switch tabs continues off-screen.

STEPS:
1. Have too many tabs open - let them go off the screen.
2. `CMD+OPTION+ARROW` repeatedly until focusing on a tab that is not visible.

Desired behaviour:
Tab is focused.
Row of tabs scrolled to make focused tab visible.

Actual behaviour:
Tab is focused.
Tab remains off-screen.


I wonder if some sort of tabOnFocus function should be used to move the whole thing into view... Would solve both of these issues. Would be better than an external function trying to move things around in reaction to to some set of events.

**Comment by alexmnazarenko** [comment]
I second this.

I often work with a lot of opened files (and I need them open, e.g. doing some mass refactoring).

1. Tabs go off-screen, 
2. I don't know what tab is next/prev
3. I get lost and cry

**Comment by ocoka** [comment]
+1

**Comment by v3ss0n** [comment]
@as-cii  can you look into this? since @izuzak  is not active here anymore and , none of the community found a way to fix it yet.

**Comment by lee-dohm** [comment]
This is something we want to fix eventually, not by having an option, but by making it the default behavior. As far as fixing this now, this is of fairly low priority for us relative to the many, many bugs, things that need to be made more performant and other improvements Atom requires. This is something that we would accept a PR for, so long as it was made the default behavior and did not add another option.

**Comment by Ben3eeE** [comment]
This has been bothering me as well so I made an attempt to add this in https://github.com/atom/tabs/pull/375

**Comment by v3ss0n** [comment]
@Ben3eeE  its working very well! thank you very much.
Please merge this
