### ISSUE TITLE
Shift + ScrollWheel should only scroll the tab-bar , should not select (switch) tabs. 

### ISSUE THREAD

**Issue by v3ss0n** [atom/tabs#139]
Currently , it also switches the tabs .

**Comment by lee-dohm** [comment]
Is this on a particular platform? I don't see the behavior you're mentioning on OS X.

**Comment by v3ss0n** [comment]
On linux , KDE

**Comment by izuzak** [comment]
@v3ss0n You can turn that behavior off in the settings of the tabs package:

![screen shot 2015-05-13 at 17 20 12](https://cloud.githubusercontent.com/assets/38924/7614010/5d27ad72-f994-11e4-8f8f-08186338ebe9.png)

Atom > Settings > Packages > Tabs > Tab Scrolling

**Comment by v3ss0n** [comment]
This totally disable tab switching on scroll wheel.
But Thanks ! You saved my day , again! I can live without it.

**Comment by jerone** [comment]
I still think that when one <kbd>Shift</kbd> + Scroll (with many tabs open) and the option `Tab Scrolling` is enabled, tab scrolling shouldn't happen at the same time as overflow scrolling is happening. Now both tabs are switched and the tab-bar is scrolled, confusing users.

Windows 7 64-bits
Atom 0.199.0

**Comment by v3ss0n** [comment]
Disabling tab scrolling help a bit , but i also do consider while enabling  shift+ tab scrolling it should not Overflow Scroll and tab switch at the same time.

@izuzak  Let us know what do you think?

**Comment by izuzak** [comment]
> @izuzak Let us know what do you think?

I think that makes sense. In my previous comment I just wanted to point out you can disable that feature completely if it's causing problems, not that you need to close the issue or that your request doesn't make sense.

**Comment by v3ss0n** [comment]
Thanks . i understand , don't worry.

**Comment by v3ss0n** [comment]
:+1:
