### ISSUE TITLE
Use git status colors in tab titles

### ISSUE THREAD

**Issue by grizzilus** [atom/tabs#142]
This is a feature request to match the color of the titles of tabs to those in the tree view based on the git status of the files. There is currently a package for this (`git-tab-status`), but I think it would be nice to have on the core tabs package to match the functionality of the `tree-view` package. (Also, I don't think `git-tab-status` is compatible with all themes. There was a point where a change in `one-dark-ui` conflicted with the methodology of that package.)

And having the `status-added` and similar classes in the core tabs package could allow theme designers to use those as well. For example, the `one-dark-ui` package has a blue bar on the left side of the active tab. This color could be changed to the color for the git status of that file. (That trivial example would obviously need some extension for active vs. inactive tabs, but the point is that this information could be integrated into themes in clever ways.)

**Comment by mnquintana** [comment]
:+1: I'm definitely on board with this – I've wanted this for awhile now.

**Comment by acontreras89** [comment]
Just created #152 to add this functionality.

**Comment by grizzilus** [comment]
This was completed in #152 so I'll close this.

**Comment by jakesankey** [comment]
This great news. I am the dev of git-tab-status, I will unpublish the package. Glad it made it into Tabs!

**Comment by acontreras89** [comment]
@jakesankey :ok_hand:
thanks for your package, I used to use it until I decided to include it in the tabs core package

**Comment by kankaristo** [comment]
This doesn't seem to be working for me... The file names are colored in the tree view, but not on the tabs.

The git-tab-status package is working fine, but "Enable VCS Coloring" isn't.

**Comment by mnquintana** [comment]
@kankaristo It won't work if you have both enabled. You'll need to uninstall or disable git-tab-status first, then Enable VCS Coloring.

**Comment by kankaristo** [comment]
I did that (first disabled, then uninstalled).

I just noticed that this doesn't seem to be working well with symlinks...

The tabs are colored fine if the project is in a normal directory, but I have a few projects where the project directory's parent directory is a symlink to an external drive, and the coloring is broken for those. The coloring works in tree-view and with git-tab-status.

**Comment by mnquintana** [comment]
@kankaristo Hmmm, would you mind making a new issue for that so we can investigate further? (That's why we didn't enable it by default, just to be able to catch any lingering bugs.) Thanks!

**Comment by kankaristo** [comment]
Sure. :)

**Comment by acontreras89** [comment]
Point to the issue here and I'll start working on it right away :)

**Comment by kankaristo** [comment]
Opened an issue here: https://github.com/atom/tabs/issues/182
