### ISSUE TITLE
"Use preview tabs" says tabs will stay open if double-clicked, but they don't

### ISSUE THREAD

**Issue by lee-dohm** [atom/tabs#156]
Using Atom v0.206.0-4941229 on Mac OS X 10.10.3.

![screen shot 2015-06-02 at 7 38 29 pm](https://cloud.githubusercontent.com/assets/1038121/7951649/0ca54bf4-095f-11e5-9aa6-84c1474b35bd.png)

### Repro Steps

1. Open Atom
1. Open Settings View
1. Navigate to Tabs package settings
1. Ensure "Use Preview Tabs" is checked
1. Close Settings View
1. Double-click any file in Tree View

**Expected:** Tab's title to not be italic (italic is the indicator that it is temporary)
**Actual:** Tab's title is italic

1. Double-click another file in Tree View

**Expected:** Second tab to open
**Actual:** New file overwrites the tab of the original file

**Comment by lee-dohm** [comment]
I figured it out while trying a few more things. If you double-click the tab itself (not the file in the Tree View), it becomes permanent. So ... perhaps not a bug? I still think this will be a common misconception.

**Comment by mnquintana** [comment]
This only works currently if the tab itself is double-clicked, but not if the filename is double-clicked from the tree-view. I think we'd have to tweak the behavior of clicking on files in the tree-view a bit. Currently, single-clicking opens a file but keeps focus on the tree-view, and double-clicking focuses the editor; we'd have to change it so that single-clicking opens a preview tab and focuses the editor, and double-clicking opens the file and focuses the editor.

**Comment by mnquintana** [comment]
FWIW we probably should add this enhancement because it's how the feature works in Sublime and it would feel much more intuitive, I think.

**Comment by lee-dohm** [comment]
> we'd have to change it so that single-clicking opens a preview tab and focuses the editor

The reason why single-clicking does not focus the editor is so that you can click a file in the Tree View and press <kbd>Backspace</kbd> to delete it.

**Comment by mnquintana** [comment]
Ah alright then, so updated:

### Current behavior

- Single-clicking opens a file but keeps focus on the tree-view
- Double-clicking focuses the editor

### Proposed behavior

- Single-clicking opens a preview tab but keeps focus on the tree-view
- Double-clicking opens the file as a regular tab and focuses the editor

Does that seem reasonable?

**Comment by lee-dohm** [comment]
Yes, it does :grinning:

**Comment by mnquintana** [comment]
This is a bit trickier than I thought at first – I think tabs will have to provide a service for tree-view to consume in order for tree-view to be aware of Preview Tabs.

**Comment by acontreras89** [comment]
@mnquintana , @lee-dohm thanks for the effort!
looking forward to having this enhancement

**Comment by cjihrig** [comment]
I'm extremely excited to have this - preview tabs have probably been my biggest pain point with Atom. You mentioned that it is trickier than you originally thought. Any estimate on when this will be ready?

**Comment by hawsome** [comment]
I just came here to say, "Yes, this, please". I expected Sublime behavior. Thanks!

**Comment by AdamBuczynski** [comment]
Would be great to have file double clicking open them permanently, instead of having to double click the tab.

**Comment by cstockton** [comment]
I want to +1 this as well, just noticed it when I updated packages and saw sublime text was deprecated and wouldn't work anymore.

**Comment by alexrussell** [comment]
Just wanted to :+1: this issue. I did subscribe as I once read repo owners use number of subscribers to work out how many people care about a given issue, but I'm not sure how true that is (I certainly can't see an easy way (admittedly as a non-package-owner) to sort by number of subscribers, etc.).

**Comment by zirho** [comment]
+1

**Comment by miduga** [comment]
For those who come from Sublime Text this addition is a must. Thanks!

**Comment by zirho** [comment]
I think this is fixed. 
I updated it and works fine now.

**Comment by adambuczynski** [comment]
It is supposedly fixed in 1.6.0 beta of Atom. See also https://github.com/atom/atom/issues/9165

**Comment by alexrussell** [comment]
In the version I use (the Beta) preview tabs now works exactly as expected - single click in tree = preview, double click in tree = permanent, double click preview tab titlebar (or edit text buffer in some way) = preview becomes permanent.

**Comment by lee-dohm** [comment]
I'm also adding some stuff to the Flight Manual about this:

https://github.com/atom/docs/pull/163

**Comment by ddavison** [comment]
@lee-dohm et al.. since Preview Tabs was previously the sublime tabs package, here is the "spec" of features that was offered by sublime tabs.

https://github.com/ddavison/sublime-tabs/issues/43#issuecomment-71578025

double clicking to make tabs permanent was built-in.  

*fwiw*

**Comment by iamsteadman** [comment]
Can I ask how to disable this option now that it's disappeared? I accept that I'm in the minority but I massively dislike having to think beforehand if I have to single- or double-click a filename based on whether I might edit it in the future... so I need to be able to stop this behaviour from happening, since it's not something I enabled.

Where's the option to bring back the expected, consistent behaviour, where single-clicking opens a new permanent tab?

Thanks!

**Comment by JTabel** [comment]
@iamsteadman I just foundYou can disable it in the core setting "Allow Pending Pane Items". When you uncheck the box, it will use the old behaviour.

**Comment by iamsteadman** [comment]
@JTabel Perfect, you're a lifesaver. Thank you.

**Comment by msssk** [comment]
Atom updated to 1.7.1 on Windows 10 and the old behavior is completely gone for me. I have unchecked "Allow pending pane items" and now single-clicking a file does nothing.

Expectation: disabling this option should give me the old behavior, where I could open a file with a single click.
Result: disabling this option gives me new behavior, where there's no preview at all, single click does nothing, I always have to double-click to open a file.

**Comment by acontreras89** [comment]
@msssk there's already a PR in the `tree-view` package (https://github.com/atom/tree-view/pull/804) to address this.
