### ISSUE TITLE
Tabs become temporary when dragged to another pane

### ISSUE THREAD

**Issue by acontreras89** [atom/tabs#161]
When a tab is dragged from one pane to another, it's added as a temporary tab regardless of its original state.

Steps to reproduce:
* Select a file in tree-view
* Double click the tab to remove it's preview status
* Drag the tab to another pane

**Comment by 50Wliu** [comment]
See also #155 which fixed a similar case.

**Comment by kevinsawicki** [comment]
I pushed a fixed to make dropped tabs moved between panes permanent, this felt right to me after trying a few different things, and it makes it consistent with split tabs which also start as permanent.

**Comment by acontreras89** [comment]
Thank you sir! :thumbsup:
