### ISSUE TITLE
Tabs restoring with Preview Tabs enabled.

### ISSUE THREAD

**Issue by d4rkr00t** [atom/tabs#163]
When i try to reopen closed tabs they opens in preview tab and replace each other every time i press `cmd+shift+t`. It seems like a bug.

**Comment by acontreras89** [comment]
I was about to report this problem too :+1:

**Comment by benogle** [comment]
This is fixed on master and the 1.5.x line which is in beta now. See https://github.com/atom/atom/issues/9165 for more information.

**Comment by d4rkr00t** [comment]
Wow, great, thanks!
