### ISSUE TITLE
Tabs do not become permanent when saved — or we need another shortcut

### ISSUE THREAD

**Issue by peterjeliot** [atom/tabs#165]
As far as I know, there is no keyboard shortcut to make a temporary tab become permanent. In other editors, and in atom-sublime-tabs, saving a file makes the tab permanent, *even if the file is not changed*. I would like us to mimic this behavior.

If there's a keyboard shortcut that exists and I don't know about it, we should add a hint text by the option or something. I don't want to have to add and remove text from a file just to get its tab to stick.

**Comment by 50Wliu** [comment]
You can bind `tabs:keep-preview-tab` to a keyboard shortcut in the meantime.  You can also double-click the tab title.

**Comment by peterjeliot** [comment]
Thanks. I prefer not to use the mouse, but mapping it myself works for now.

**Comment by kevinsawicki** [comment]
Thanks for bringing this it up, saving will clear the preview tab in the next Atom release, 0.208

**Comment by peterjeliot** [comment]
Hooray!
