### ISSUE TITLE
Next/Previous File in Stack

### ISSUE THREAD

**Issue by ssteinker** [atom/tabs#17]
What is about a "Next/Previous File in Stack"-Shortcut like in Chrome? 
"ctrl + TAB" for next file 
"ctrl + shift + TAB" for previous file 

cheers,
Sven

**Comment by joerx** [comment]
+1

**Comment by johnbacon** [comment]
+1

**Comment by baffles** [comment]
+1 from me as well.

Any updates on this front? This is pretty much my only complaint about Atom at the moment, and it's a fairly annoying/jolting issue.

**Comment by ghempton** [comment]
Definitely a needed feature. Tab history has some quirks.

**Comment by jaywink** [comment]
:+1: for this, was surprised to see this doesn't already work :(

**Comment by thomasthorsen** [comment]
This is definitely needed, the default behaviour is not useful

**Comment by kdemarest** [comment]
Yes, absolutely. It simply works wrong as-is. Perhaps there is a package to fix this clearly wrong behavior?

**Comment by 50Wliu** [comment]
If this is to be "fixed", I would like it to be a config option please :).

**Comment by Josh-Dykstra** [comment]
+1

**Comment by blachniet** [comment]
:+1:  - a config option to change this behavior would be great.

**Comment by mrkaspa** [comment]
Any news about this? I only keep using ST because of this

**Comment by defel** [comment]
Hi *,

i am using [tab-switcher](https://atom.io/packages/tab-switcher) now and are happy with it. 

Here is my `keymap.cson`: 

```cson
'atom-workspace':
  'ctrl-tab': 'tab-switcher:next'
  'ctrl-shift-tab': 'tab-switcher:previous'
```

**Comment by batjko** [comment]
@mrkaspa If that's the only thing keeping you from using Atom, do have a look at either [tab-switcher](https://atom.io/packages/tab-switcher) or [tab-history](https://github.com/guillaume86/tab-history) as suggested people above.

**Comment by timscott** [comment]
@defel The shortcoming of [tab-switcher](https://github.com/oggy/tab-switcher) is that it does not focus the last tab when closing a tab. I have filed [an issue](https://github.com/oggy/tab-switcher/issues/11) but the author says it needs to come form Atom core. IMO this is very important and something every ST3 convert just expects.

**Comment by defel** [comment]
@timscott looks like the needed pull request was accepted and will be merged soon. Thanks for this info.

**Comment by zdrummond** [comment]
+1

This is expected-behavior in all text editors I have used...

**Comment by astorije** [comment]
:+1:

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by 50Wliu** [comment]
This has since been added.
