### ISSUE TITLE
Files opened from external source should not be temporary

### ISSUE THREAD

**Issue by adambuczynski** [atom/tabs#170]
See also #164 

Files that I open from finder or any other external source should also be opened permanently.

I think the fact that basically *all* files that are opened now are opened in "temporary mode" breaks your work flow. You don't want to have to remember to double click a file to make it permanent every time after opening. Opening files permanently should be the default, with the temporary view mode only being activated when you single click on a file in the tree view.

Try opening 3 files from finder/external file browser in a row. Only the last one will be open, unless you double click the tabs.

**Comment by acontreras89** [comment]
:+1:

**Comment by adambuczynski** [comment]
I really think this is a bug, rather than an enhancement. Today I was opening files on an FTP server via transmit for some quick editing, and after having opened the 5 files that I needed, I went to Atom to work on them, but found that it had only kept the last file that I opened open in it's tabs, so I had to go and open them again, one by one, then double click the tab to force the file to stay open. This is really sub optimal and a defect in my opinion.

**Comment by thedaniel** [comment]
@kevinsawicki we talked on our call today about making tabs default to permanent and require some option passed in the call to make them temporary to avoid future bugs like this - today the tree-view would be the only caller that would initiate temporary tabs - does that make sense?

**Comment by adambuczynski** [comment]
Seems like a good idea in my opinion.

**Comment by acontreras89** [comment]
sounds great :smile: 
and it's likely to simplify some cases, like double-clicking in tree-view to open the file without preview mode.

**Comment by crazymykl** [comment]
@thedaniel: cmd-p should also make temporary tabs.

**Comment by kevinsawicki** [comment]
> does that make sense?

Yup, makes sense

**Comment by adambuczynski** [comment]
Doesn't make sense to me, see other issue raised about opening files in
fuzzy finder. At least make it a configurable option.

**Comment by adambuczynski** [comment]
@crazymykl I disagree, see this issue: https://github.com/atom/tabs/issues/164

Everything except single click in tree view should make permanent tabs. If you're in fuzzy finder, you are using the keyboard, and it's not a big effort to hit cmd-w after cmd-p. When you want to open a bunch of files with cmd-p to work in however, it's a real hassle to have to switch from keyboard to mouse in order to double click the tab to make them permanent before you can open the next file.

@thedaniel Maybe it's an idea to also make the temporary state of a tab keyboard toggle-able.

**Comment by crazymykl** [comment]
Doesn't hitting any key then backspace make it permanent already, no mousing needed?

Since there are differences of opinion, a setting seems prudent.

**Comment by adambuczynski** [comment]
I don't really want to incorporate having to hit a random key + backspace for every single file that I open into my daily workflow....

Atom is supposed to make my life easier, not harder. But I agree, if this could be turned into sensible settings, everyone would be happy. E.g.:

Use preview tabs for:
- Files opened from external source: false
- Files opened via tree view with single click: true
- Files opened via tree view with double click: false
- Files opened via fuzzy finder: false

**Comment by thomasjo** [comment]
> @kevinsawicki we talked on our call today about making tabs default to permanent and require some option passed in the call to make them temporary to avoid future bugs like this - today the tree-view would be the only caller that would initiate temporary tabs - does that make sense?

This is definitely the way to approach resolving this issue. Doing the opposite seems rather silly, since there are far fewer cases where we want to open a tab in preview mode than not. Not having looked at the code for this, my immediate thought is that this must surely be the easiest approach, and the one requiring minimal changes.

**Comment by alexrussell** [comment]
:+1: for the permanent-as-default and preview/temporary for single clicking in treeview **only**.

**Comment by acontreras89** [comment]
Is someone working on this? If not, I'd gladly take the _challenge_ :stuck_out_tongue:

**Comment by lee-dohm** [comment]
I don't see any open PRs attached @acontreras89. I'd say go for it :grinning:

**Comment by acontreras89** [comment]
:ok_hand: working on it, @lee-dohm

**Comment by PCateNumbersUSA** [comment]
Would love to see this setting added as well.

**Comment by adambuczynski** [comment]
@acontreras89 any luck?

**Comment by acontreras89** [comment]
I'm sorry @adambuczynski, I will try to come back to you as soon as possible

**Comment by adambuczynski** [comment]
Is there any chance someone can pick this issue up to progress it? It's one of the most persistent day-to-day frustrations that I still encounter when using Atom, and it's been open for 5 months already, while it seems like a fix should not be too much work to implement.

I'd offer my help to fix it, but I don't know much about the internal workings of Atom. However, if no one else can work on this issue, I can see if I can help.

**Comment by benogle** [comment]
This is fixed on master and the 1.5.x line which is in beta now. See https://github.com/atom/atom/issues/9165 for more information.
