### ISSUE TITLE
Open files not from Tree View in preview tabs

### ISSUE THREAD

**Issue by 190n** [atom/tabs#172]
Can you make it so that files also get opened in preview tabs when you open them from the Open dialog?

**Comment by acontreras89** [comment]
Isn't that the current behavior? 
And yet I feel like preview tabs should only be activated when single clicking a file in tree-view. Just like requested in #170

**Comment by mnquintana** [comment]
@190n That's the current behavior - going to close this. Please comment though if I'm misunderstanding.
