### ISSUE TITLE
Close Tab Actually Closes Pane

### ISSUE THREAD

**Issue by Verexa** [atom/tabs#174]
When right-clicking on a tab to bring up the menu. Selecting 'Close Tab' closes the Pane and all of the Tabs in that Pane.
Clicking the cross button on the tab closes a single tab correctly. Clicking 'Close Other Tabs', 'Close Tabs to Right', etc. works correctly.
Therefore the action 'Close Tab' does is the same as pressing 'Close Pane'. Shouldn't these be different behaviors?

Expected Behavior: Close a single Tab inside of a Pane.
Actual Behavior: Closes the Pane and all Tabs on it.

OS: Windows 7 Enterprise (64 bit)
Atom Version: 0.208.0

**Comment by mnquintana** [comment]
The option for the behavior you're describing already exists – just go to Settings and uncheck Destroy Empty Panes.

**Comment by kevinsawicki** [comment]
I think this might have been #175 which is now fixed
