### ISSUE TITLE
Closing tab from context menu also closes previous tab

### ISSUE THREAD

**Issue by olmokramer** [atom/tabs#175]
As [reported on discuss](https://discuss.atom.io/t/close-tab-menuitem-closes-more-than-one-tab/17588), closing a tab from the context menu also closes the previous tab. This doesn't happen when I close the tab from the command palette or using <kbd>ctrl+w</kbd> keybinding.

I could reproduce it on both Atom 0.208.0 and 0.209.0-b903302.

**Comment by kevinsawicki** [comment]
Thanks for reporting this, this was a regression from https://github.com/atom/tabs/pull/166 which is now fixed and will be in the next Atom release, 0.209

**Comment by olmokramer** [comment]
Wow that was a quick one :) Thanks!
