### ISSUE TITLE
Clicking a tab does not focus its TextEditor

### ISSUE THREAD

**Issue by ssorallen** [atom/tabs#176]
1. Open two tabs
2. Click the inactive tab

The editor of that tab does not gain focus when the tab is activated. If you navigate with the keyboard, say via Cmd + 1 and Cmd + 2, the editor *does* gain focus.

Particularly strange case:

1. Open two tabs
2. Highlight text in the active tab
3. Click the inactive tab to activate it
4. Click the other tab (the one with the highlight) to re-activate it
5. The text is still highlighted, which *looks* like the editor has focus but typing does nothing

**Comment by kevinsawicki** [comment]
I think this may have just been fixed in https://github.com/atom/tabs/pull/150

**Comment by mnquintana** [comment]
@ssorallen This should've been fixed in #150, which will be in Atom 0.209.0. When 0.209.0 is out, if you can still reproduce this, feel free to comment / reopen.

**Comment by ssorallen** [comment]
Great, thanks. That change might also fix #93.

**Comment by ssorallen** [comment]
Actually never mind, not exactly the same issue. #150 looks good though, thanks.
