### ISSUE TITLE
Stick preview pane when save (cmd+s)

### ISSUE THREAD

**Issue by freemanoid** [atom/tabs#179]
Currently if I want to stick the preview pane I need to either type something inside and delete it or double click on the tab. 
I think it would be useful to stick the preview tab via saving by cmd + s (this is how sublime text works) or another hotkey.

**Comment by mnquintana** [comment]
What version of Atom are you using? [Saving a file opened in a preview tab should make it a permanent tab (it was added in 0.208.0)](https://github.com/atom/tabs/issues/165). In addition, there's also a Keep Preview Tab command if you right click on a preview tab, and you could map that to a keybinding if you wanted:

```cson
'atom-pane':
  'alt-K': 'tabs:keep-preview-tab'
```

**Comment by freemanoid** [comment]
Cool, thank you for pointing me, I used 0.207 and somehow missed this feature in release notes. Sorry for disturb.
