### ISSUE TITLE
Better indicate preview tab

### ISSUE THREAD

**Issue by mnquintana** [atom/tabs#180]
_From @linquize on June 14, 2015 7:51_

It would be clearer to indicate preview tab by adding some visual effects.
This allows user to easily distinguish from normal tabs.
e.g. A different background color, text color or adding a special symbol.

_Copied from original issue: atom/atom#7273_

**Comment by mnquintana** [comment]
_From @YuriSolovyov on June 14, 2015 8:36_

sublime does it using italic font for tab title

**Comment by mnquintana** [comment]
_From @linquize on June 14, 2015 8:51_

Visual Studio uses different background color and border.

**Comment by mnquintana** [comment]
_From @freemanoid on June 14, 2015 9:31_

> sublime does it using italic font for tab title

Atom works the same now.

**Comment by mnquintana** [comment]
_From @linquize on June 14, 2015 9:41_

I notice that: Italic font, like sublime

**Comment by Ben3eeE** [comment]
Atom has italic font for pending pane items as the comments here says. Closing this as resolved as there is no clear suggestion for what would be an improvement compared to the current way of indicating pending pane items.
