### ISSUE TITLE
Cannot drag inactive tabs without focusing them first

### ISSUE THREAD

**Issue by matthewmorek** [atom/tabs#190]
You have to make a tab/pane active first, before you are able to click-drag it, to reorder, or move across to another pane.
#### Steps to reproduce:
1. Open up a file in Atom.
2. Split the panes in whichever way you want.
3. Click on either pane/tab to make it active/bring it to focus.
4. Try click-dragging the other file into the opposite pane.

**Comment by infogulch** [comment]
This is still a problem.

More specifically, it manifests when you attempt to drag a tab that's *not in the currently active pane*.

This also negatively affects packages that rely on `tabs` for their functionality, like morassman/tabasco#6 which allows you to split panes by overloading dragging tabs.

**Comment by infogulch** [comment]
After a tiny bit of investigation I found that the `onDragStart` event is never fired on tabs that are in an inactive pane, for any event listener.

I can use the debugger but I'm not a web dev and I have no idea where to proceed from here.

**Comment by 50Wliu** [comment]
This seems to have been resolved - I can no longer reproduce.
