### ISSUE TITLE
[Feature Request] Color by project

### ISSUE THREAD

**Issue by Stanzilla** [atom/tabs#199]
I'm not quite sure if themes already have access to that info, but being able to color tabs differently depending on the project they belong to would be neat. 

A non ugly way for example could be something like a 1px border but that's up to the theme then.

**Comment by thomasjo** [comment]
This sounds like a great idea for a package! A few existing packages for inspiration:
 - https://atom.io/packages/project-colorize
 - https://atom.io/packages/color-tabs
