### ISSUE TITLE
Add tooltip indicating tab file location

### ISSUE THREAD

**Issue by gjtorikian** [atom/tabs#2]
If each tab div had some `data-title` attribute, users could get the path to the file they're looking at when they're hovering over a tab:

![screen shot 2013-09-16 at 8 10 18 pm](https://f.cloud.github.com/assets/64050/1154476/b69cae86-1f46-11e3-85d5-1e9695406aa2.png)

Super bonus points if I can copy that text to the clipboard somehow, which is what I want to do most of the time ( _e.g._ to run a single file in a test suite).

**Comment by roostercrab** [comment]
How do we turn this off though, I hate it
