### ISSUE TITLE
Keep preview open whenever the pane is double-clicked

### ISSUE THREAD

**Issue by brianmhunt** [atom/tabs#202]
Right now one has to either modify the file, or double-click the *tab*.

It would be helpful in some use cases to be able to double-click anywhere in the the tab pane to trigger its persistence. This would save time having to focus on the small tab with the mouse and clicking, or click-edit-unedit, for tabs one just wants to keep open. There doesn't seem to be a downside as there's no competing use-case for double-clicking a tab pane as far as I can see.

Just a thought :beers:

**Comment by ProLoser** [comment]
:+1: I agree, I believe this is also the sublime behavior too.

**Comment by ddavison** [comment]
there's also one more method.  right click the tab, and Keep Preview Tab, but that's of course a little bit more work.

Also, @ProLoser, i have the most up-to-date version of sublime and sublime doesn't keep the tab fi you double click

**Comment by ddavison** [comment]
also, @brianmhunt 

> there's no competing use-case for double-clicking a tab pane

if you double click the tab pane, it will create a new untitled tab

**Comment by brianmhunt** [comment]
@ddavison – I do not see that behaviour. Double-clicking in the tab pane with an document displayed causes highlighting of any words under the cursor.

**Comment by benogle** [comment]
This is fixed on master and the 1.5.x line which is in beta now. See https://github.com/atom/atom/issues/9165 for more information.
