### ISSUE TITLE
[Enhancement] Do not preview direct-opened tabs

### ISSUE THREAD

**Issue by ddavison** [atom/tabs#206]
*migrated from https://github.com/ddavison/sublime-tabs/issues/134*

@Epigene:

I enjoy clicking around the tree view and only opening the files in preview tab by enabling the "Use Preview Tabs" option of this package, but it is unfortunate that previewing also affects other opening scenarios.

Specifically:
* Files opened through File->Open
* Files drag-and-dropped
* Files opened through fuzzy search (Command+T)
* Files opened by doubleclicking projectwide search result lines

I would like for files opened by these methods to open in _permanent_ tabs.
Naturally, selectable options regarding the behavior of each of these cases would be best.

**Comment by lagartoflojo** [comment]
To add to this: Opening multiple files through the File->Open dialog is broken with Preview Tabs enabled, as they will all open on the same preview tab. End result is that only one of the selected files opens. Permanent tabs in this case would definitely be preferred.

**Comment by enricribas** [comment]
+1 
We have a guy refusing to switch from Sublime over this :)

**Comment by ProLoser** [comment]
:+1: I too would like to see fuzzy-search not use previews.

**Comment by justinhoward** [comment]
+1 The fuzzy search issue is what stops me from using the preview feature. Ideally, permanent tabs would be the default with a few special cases for previews. I believe sublime used previews only for single clicking in the tree and scrolling through fuzzy search (without clicking or hitting enter).

**Comment by jandlint** [comment]
With preview mode active, you can make the tab stick around by saving (even though you've changed nothing). It's not perfect, but it helps me get close to my previous workflow.

**Comment by Epigene** [comment]
@jandlint Cool trick, will tide me over for now.

**Comment by DanielSundberg** [comment]
+1 I would like to see this implemented the way @justinhoward describes it...

**Comment by Xcodo** [comment]
+1 The behaviour of drag-and-drop has been annoying me particularly this week.

**Comment by benogle** [comment]
This is fixed on master and the 1.5.x line which is in beta now. See https://github.com/atom/atom/issues/9165 for more information.
