### ISSUE TITLE
key bindings doesn't work on temporary tabs

### ISSUE THREAD

**Issue by ppires** [atom/tabs#207]
I've changed my "ctrl-shift-W" key binding to closes all tabs, instead of closing the editor. When the current tab is a preview tab, and I execute the "close all tabs" command, the editor is closed, instead of all tabs. ~~Also, when in a preview tab, "ctrl-PageUp" and "ctrl-PageDown" don't switch tabs~~ (after updating atom to 1.0.8 this stopped happening).
I've noticed that after opening a preview tab, if you change to a normal tab and then go back to the preview tab, everything works as expected.

Steps to reproduce:
* Enable "Use Preview Tabs" on tabs settings.
* Create a keybinding to close all tabs: 
```
'atom-text-editor:not([mini])':
  'ctrl-shift-W': 'tabs:close-all-tabs'
```
* Click once on a file to open a preview tab.
* Execute the command to close all tabs.

I'm using atom version 1.0.8 and the tabs package version 0.82.0.

**Comment by benogle** [comment]
This is fixed on master and the 1.5.x line which is in beta now. See https://github.com/atom/atom/issues/9165 for more information.

If you can still reproduce this on 1.5 beta, please let us know.
