### ISSUE TITLE
Tabs package causes AtomHelper process to consume 60-100% CPU on 13" Retina MacBook Pro

### ISSUE THREAD

**Issue by nicbet** [atom/tabs#211]
## Problem
Tabs package causes AtomHelper process to consume 60-100% CPU on 13" Retina MacBook Pro. This causes the machine to significantly heat up and consume excessive battery.

## Steps to Reproduce
Occurs repeatably on OS X 10.10 and 10.11. Machine is a 13" Mid 2014 rMBP. Was doing some digging into why Atom would consistently consume high CPU on my machine, regardless of whether any file was open or not. Followed advice to start with `atom --safe` and found no significant CPU consumption. Started in normal mode and disabled packages one by one, starting with 3rd party packages. Disabling 'tabs' finally received the CPU.

* Attached screenshots show tabs enabled CPU at snapshot time 61.7%. 
* Tabs disabled CPU at snapshot time 1.5%.

## Versions:
* Atom.io 1.0.19
* Tabs 0.84.0

## Screenshots
<img width="843" alt="tabs-enabled" src="https://cloud.githubusercontent.com/assets/718340/10296216/7836b6d6-6b94-11e5-9b3e-5faa5a11d920.png">

<img width="859" alt="tabs-disabled" src="https://cloud.githubusercontent.com/assets/718340/10296217/78479f1e-6b94-11e5-9113-3d14fc2a3250.png">

**Comment by benogle** [comment]
Is this repeatable? What were you doing before the 60% usage? What are the steps to get the 60% usage?

I'm definitely not seeing this. On my 2014 15" mpb, Atom uses 0.7% with tabs enabled when not focused and 3% when focused. Disabling tabs has no effect for me.

**Comment by nicbet** [comment]
Dug a little deeper - appears the cause is the UI animation for 'modified' file, e.g. added by this package https://github.com/kenwheeler/brogrammer-ui   which causes a red circle pulsate when a file has unsaved modifications. Disabling the 'tabs' package thus causes the animation not to be displayed. Not sure whether this is ultimately a tabs or a ui theme issue?

**Comment by benogle** [comment]
Definitely a UI theme issue. Feel free to open an issue on their repo.

**Comment by nicbet** [comment]
Thanks!
