### ISSUE TITLE
Extreme lag when dragging tabs

### ISSUE THREAD

**Issue by PachowStudios** [atom/tabs#226]
Whenever I drag a tab to reorder it, it lags 5-15 seconds behind.

I have tried disabling all my packages and themes, but it seems to happen even on a clean install.

![Here is a gif of the issue](http://zippy.gfycat.com/PinkWeirdGalapagosalbatross.gif)

**Comment by izuzak** [comment]
Thanks for the report, @PachowStudios. Can you post an equivalent GIF which demonstrates the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Also, can you share your OS+version and Atom version? And did this start happening recently for you or was it always slow like that?

**Comment by PachowStudios** [comment]
Sorry, I should've included more info.

I will try it in safe mode when I get home and report back. I believe this always happened, but I'm not 100% sure.

I'm running the latest Atom on Windows 10. System specs shouldn't be an issue (i7 gen 3, 16gb ram, ssd).

I just installed Atom on another computer running Windows 7 and it has no such issue out of the box. I'll pay very close attention as I install all my plugins and report back.

The strangest thing is that if this is a plugin issue, why it happened even when I had all my plugins disabled.

**Comment by 50Wliu** [comment]
> I'm running the latest Atom on Windows 10

Can you please specify *exactly* what version of Atom that is?  You can view the version in the Help menu.  (The reason I'm asking is because sometimes people *believe* they're on the latest version of Atom, but are actually 50+ releases behind)

**Comment by PachowStudios** [comment]
v1.0.19

After installing all my packages to my windows 7 install, it works perfectly. I guess I'll try a clean install on my Windows 10 machine tonight and see if that helps.

**Comment by Ben3eeE** [comment]
We have merged https://github.com/atom/tabs/pull/390 which significantly improves performance when dragging tabs. This is currently scheduled to be released in Atom 1.28.
