### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by bryansquared** [atom/tabs#229]
1. Have settings open
2. Make new window
3. Drag settings tab to new window
(edit: tested with a non-settings pane and it still threw this error)

**Atom Version**: 1.2.0-beta0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.87.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At ...\AppData\Local\atom\app-1.2.0-beta0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:586

TypeError: Cannot read property 'id' of undefined
    at EventEmitter.TabBarView.onDropOnOtherWindow (...\AppData\Local\atom\app-1.2.0-beta0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:586:20)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -1:08.8.0 core:undo (atom-text-editor.editor.is-focused)
     -1:07.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:07.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:57.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:57.6.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:56.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:56.4.0 core:paste (atom-text-editor.editor.is-focused)
  7x -0:56 core:backspace (atom-text-editor.editor.is-focused)
     -0:54.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:53.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:51.2.0 core:cut (atom-text-editor.editor.is-focused)
     -0:50.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.6.0 tabs:split-up (li.tab.sortable.active.right-clicked)
     -0:27.5.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -0:25.8.0 tabs:close-tab (li.tab.sortable.active.right-clicked)
     -0:21.6.0 pane:close (li.tab.sortable.active.right-clicked)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.9.4
python-isort, v0.0.7
python-tools, v0.6.5

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @bryansquared -- I was able to reproduce this on the latest master version.

@as-cii @nathansobo -- I think this might be related to the [recent changes around dropping jQuery](https://github.com/atom/tabs/pull/222). Mind taking a look? :thought_balloon: I was unable to reproduce the problem on version 0.86.0 of this package (version before dropping jQuery), but was able to reproduce it on 0.87.0 (after dropping jQuery).

**Comment by as-cii** [comment]
I am taking a look right now. Thanks @izuzak and @bryansquared!

**Comment by as-cii** [comment]
Okay, I narrowed it down. I am working on a fix right now, a PR should be out soon.
