### ISSUE TITLE
Files not opening in tabs

### ISSUE THREAD

**Issue by eyalw** [atom/tabs#235]
Same issue as described here:
https://github.com/atom/tabs/issues/102

**description**
1. files are open - but tabs are not showing
2. to open a file - (from fuzzy search - cmd+p) you need to actually press enter twice. the first enter is ignored.
3. I can still cycle the invisible tabs with cmt+tab

**Comment by ddavison** [comment]
do you see this when running atom in safe mode?

**Comment by eyalw** [comment]
does not reproduce in safe mode… :/I guess I’ll start disabling packages and write you back with my findings.


—
Eyal Wiener

**Comment by eyalw** [comment]
After going into safe mode (where everything worked) and then returning back, everything now works all of a sudden...

**Comment by ddavison** [comment]
glad to hear it :)
