### ISSUE TITLE
Duplicate Tab opened in split view

### ISSUE THREAD

**Issue by jonniedarko** [atom/tabs#236]
When In split view if I already have a file open and click on it in the side menu it opens another tab in the currently active split view if tab is not in that split view (but is in another one of the split views. it should be default active the already open tab in the other split view.

**Comment by anderoonies** [comment]
this seems like a result of the [searchAllPanes](https://github.com/atom/atom/blob/1fac3cb4e2608402831600c5f63dae38329251b1/src/workspace.coffee#L401) boolean defaulting to false

**Comment by ahnbizcad** [comment]
where would the place to toggle this config value be?

**Comment by Ben3eeE** [comment]
https://github.com/atom/tree-view/pull/582?

**Comment by 50Wliu** [comment]
Yep - looks like this feature will be available starting in Atom 1.9.0.
