### ISSUE TITLE
Atom not responding when trying to open files with similar paths

### ISSUE THREAD

**Issue by sidkat** [atom/tabs#242]
In a project with a file structure like 

    /a/1/index.html
    /a/2/index.html
    /a/3/index.html
    ...
    /b/1/index.html
    /b/2/index.html
    /b/3/index.html
    ...

trying to open more than two index.html files freezes Atom when tabs package is enabled (since Atom Version 1.3)

**Comment by 50Wliu** [comment]
This has been fixed in 1.4.0-beta0 already.
