### ISSUE TITLE
Keep Pending Tab - every tab

### ISSUE THREAD

**Issue by scippio** [atom/tabs#250]
After update when I open some file now.. Every tab have "Italic" file name and I must right click on it a set "Keep Pending Tab" because when I open another file this file closed :(

It's "new feature"? Or I'm missing something new settings like "kepp every new tab pending"?

**Comment by Saucy** [comment]
Uncheck "Use Preview Tabs" in the Tabs package.

(Btw you can also double click the name of the file to "keep it")

**Comment by scippio** [comment]
don't have this option:

[![https://gyazo.com/09aee43810dcb3cadabbcbfc1b055259](https://i.gyazo.com/09aee43810dcb3cadabbcbfc1b055259.png)](https://gyazo.com/09aee43810dcb3cadabbcbfc1b055259)

**Comment by lee-dohm** [comment]
In the latest versions of Atom, pending files are the default and there is no option to disable the behavior. There are multiple ways to "confirm" a pending file:

1. Double-click the tab (if you have the tabs package enabled)
1. Double-click the file in the tree-view (when opening or already opened ... works either way)
1. Edit the contents of the file
1. Save the file

Let us know if you have any more questions :grinning:

**Comment by digitalmaster** [comment]
@lee-dohm Looks like this doestn work for certain file types. If i click an `.html` or `.js` this works as expected.. However, if i click on an image it creates confirmed tabs for all of em. I have the latest beta build.

**Comment by lee-dohm** [comment]
@digitalmaster Please open a new bug for your Issue and @-mention me on it.

**Comment by digitalmaster** [comment]
@lee-dohm Done. Thanks

**Comment by dannygoncalves** [comment]
Woah, sorry but this feature is actually not an improvement.

**Comment by digitalmaster** [comment]
@dannygoncalves can you be a bit more specific?

**Comment by scottzirkel** [comment]
Wow, this was very confusing for me. Glad I found this post. 

I would expect the opposite behavior for this. Double clicking opens the pending tab, single opens a normal tab. For me at least, the pending tab would be used sparingly. I like the idea of it, but if it's either default or disable, I've disabled it.

**Comment by tylerkidd** [comment]
This gets me every time... I jump through a lot of files, sort of "staging" what I'm going to be working on. I would really appreciate this to at least be an optional "feature" that can be turned on or off.

**Comment by 50Wliu** [comment]
@tylerkidd There's an option for it now - go to Settings and uncheck the "Allow Pending Pane Items" option.

**Comment by tylerkidd** [comment]
@50Wliu - thank you for directing me there! I was looking at the Tabs package, which was apparently the wrong place. Appreciate your quick reply too, thanks!

**Comment by 50Wliu** [comment]
Yeah, the setting used to be under Tabs, but it got moved to core in 1.6.0 after the whole concept of "pending tabs" was revisited.

Glad you solved your problem :smile:.

**Comment by backspaces** [comment]
Agreed, this was unexpected/surprising behavior.  So much so that I was just writing a new Issue when I saw this thread. 

Thanks for clarifying. Maybe I'll get used to it, and it can help keep the tab bar "clean". I'm sorta interested how folks use this feature? 

I found it odd that cmd-P file choosing was non-pending, thus differing from the Tree View default of pending.

**Comment by babineaum** [comment]
Just another comment. The single click to open files follows along the same route as a lot of other applications. This new double click is just a new way to handle "opening" the file. We will have to get used to this option.

However my comment that is a bit on the negative side is that I don't see this new feature as an actual "preview". Preview to me means that it would be temporary to the view and would go away after you have performed some action like, clicking on another "opened" tab. But thats just my 2 cents.

**Comment by 50Wliu** [comment]
> Preview to me means that it would be temporary to the view and would go away after you have performed some action like, clicking on another "opened" tab.

Can you please open a new issue for this on atom/atom?

**Comment by baash05** [comment]
So is there a way to turn it off.. I don't need pending tabs.

**Comment by ceremcem** [comment]
This behaviour was actually annoying to me at first (till now) but when I found this issue, I thought about it twice, and it seems it *might* be a feature: 

We sometimes need just looking at the file contents, without the intent of editing them. So without the "not pending tab by default" *feature*, we have to close every tab we "just looked at". 

I was going to [disable it](https://github.com/atom/tabs/issues/313#issuecomment-215610050), but decided to give it a new shot.

**Comment by heymartinadams** [comment]
@lee-dohm the way to make this stand out as a _feature_ (as opposed to an annoyance, as can be seen from these comments here) is to make the look of a preview tab **completely different** from the look of a regular tab (and simply italicizing the file name isn’t different enough).

Thanks! 🙌

**Comment by Fedcomp** [comment]
by the way i was completely annoyed by this behavior for years, and only now decided to figure it out.
Yes indeed, i didn't notice italic name and didn't understand how to make them stay, this behavior was super annoying.

**Comment by UnknownWitcher** [comment]
Finally, I thought this was a permanent feature, was going to uninstall and use vscode until I found this post, looks like 5 years later and this feature is still causing problems lol.
