### ISSUE TITLE
Duplicate tree-view ‘Rename’ functionality to tabs

### ISSUE THREAD

**Issue by danielbayley** [atom/tabs#251]
Namely a matching contextual menu item that works from tabs rather than only being available in tree-view.

**Comment by anderoonies** [comment]
`tree-view` relies on [move-dialogue](https://github.com/atom/tree-view/blob/master/lib/move-dialog.coffee) to accomplish (and does so well)—what's the best practice for using the functionality from another package? it doesn't seem worth adding it as a submodule for one file.
