### ISSUE TITLE
Dragging tabs does not work

### ISSUE THREAD

**Issue by Daniel15** [atom/tabs#265]
I recently upgraded from Atom 1.1.0 to 1.5.3, and now dragging tabs does not work. I'm unable to drag tabs to other panes, or even rearrange them within the same pane. Any ideas on how to debug this?

Installed user packages:
```
atom-yeoman, v0.3.15
editorconfig, v1.2.4
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
json-schema, v0.1.15
language-babel, v2.15.4
language-ini, v1.14.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
minimap-find-and-replace, v4.4.0
minimap-selection, v4.3.1
move-panes, v0.2.0
nuclide, v0.118.23098490
omnisharp-atom, v0.26.11
tool-bar, v0.2.0
visual-studio-dark-syntax, v0.1.0
```

**Comment by 50Wliu** [comment]
Can you try safe mode (`atom --safe`)?  If that works, you can use @mark-hahn's [package-cop](https://atom.io/packages/package-cop) package to try to pin down the troublesome package that's causing your issue.

**Comment by Daniel15** [comment]
Package cop is awesome! It helped me determine that `omnisharp-atom` was causing the issue. Thanks!
