### ISSUE TITLE
File preview does not work for images

### ISSUE THREAD

**Issue by digitalmaster** [atom/tabs#266]
Looks like pending tabs don't work for certain file types. If i click an .html or .js this works as expected; you see a preview of the file but tab does not stick around unless perform and confirmation action (ex Double Click). 

However, if i click on images it creates confirmed tabs for all of em automatically. 

FYII have the latest beta build.

CC: @lee-dohm 

![image](https://cloud.githubusercontent.com/assets/1279335/13276380/7ea4b0a6-da73-11e5-90b8-a9254aaa5853.png)

**Comment by kuychaco** [comment]
Thanks @digitalmaster. Fixed via https://github.com/atom/atom/pull/10959 and related PRs.

**Comment by digitalmaster** [comment]
@kuychaco awesome!
