### ISSUE TITLE
Regression: double clicking an item in the tree view will no longer unpreview / terminate pending state

### ISSUE THREAD

**Issue by forivall** [atom/tabs#269]
this was originally introduced in https://github.com/atom/tabs/commit/73658a9391ce91aa60c43dd710b3a6fc4c816df9 and no longer works since the refactor from preview -> pending

**Comment by BinaryMuse** [comment]
This should be fixed in master after atom/atom#10959 and related change sets, available in 1.6.0-beta7 and beyond. If you find you're still having the issue on the new releases, please feel free to create a new issue here and let us know what version of Atom you're on.

**Comment by forivall** [comment]
Thanks! I've been noticing a number of other, subtle & hard to reproduce bugs with pending tabs, and I hope \*crossing fingers\* that it'll be solved.
