### ISSUE TITLE
Tab bar never hides in splits with disabled "Always Show tab bar" 

### ISSUE THREAD

**Issue by ijanos** [atom/tabs#275]
After splitting the editor and the tab bar appears it will never disappear despite showing only one tab per split. With the `Always show tab bar` setting disabled I expect that splits with one tab will hide their tab bar. Initially upon split creation they do hide it but once it appears it will stay there.

**Comment by anderoonies** [comment]
this is a result of how [shouldAllowDrag](https://github.com/atom/tabs/blob/3ec77a46b737894af04bebb68e614d73b1208695/lib/tab-bar-view.coffee#L179) works—if it's refactored to, for example,
```coffee
shouldAllowDrag: ->   
  (@pane.getItems().length > 1) or
  atom.config.get('tabs.alwaysShowTabBar') and (@paneContainer.getPanes().length > 1)
```
then it has what i think is your intended result. the only problem then is what to do when dragging a tab onto the pane without a tab bar. ideally it should un-hide to allow it to be added—i can look into it in a bit.

here's what that change in `shouldAllowDrag` looks like
![hide-tab-bar](https://cloud.githubusercontent.com/assets/6645121/13465896/39e72544-e05d-11e5-9da7-d66eadd2feec.gif)

**Comment by anderoonies** [comment]
after thinking about this a bit it seems like it's not a bug—ending up in a case where a pane has no tab bar means it's impossible to move the item to another pane/move items to that pane. maybe the change should be to have the tab bar in the new pane immediately after split.

**Comment by ijanos** [comment]
Then what is the point of the Always show tab bar setting? 

I like the idea of the tab bar appearing if I drag another tab to the top part of a pane. Constantly showing a tab bar visual clutter if only one tab is open in the pane and it is wasted space with a horizontal split.

**Comment by anderoonies** [comment]
as far as i can tell it only applies to an editor with 1 tab and 1 pane. 
i agree that tab bar should appear when dragging and i can write that but the logic for showing/hiding probably shouldnt be in `shouldAllowDrag`

**Comment by ijanos** [comment]
If it applies to one editor with one pane then this issue is not a bug report but a feature request :) 

But seriously, the current status of this is not consistent and personally I prefer no tab-bars (somewhat similarly how Visual Studio Code does things, with no tabs at all). 

If you decide this is not how atom should work maybe the whole `Always show tab bar` settings should be removed and the feature propagated to a 3rd party package that removes tabs.

**Comment by lee-dohm** [comment]
I agree that this is a bug.

**Comment by anderoonies** [comment]
i implemented how i think this should work with hiding/unhiding, visible in the attached gif
i'll have to think of the best way to write specs for this, though. i can put up a PR now if you'd like or wait until i have specs written

![hide-tab-bar](https://cloud.githubusercontent.com/assets/6645121/13503409/def87376-e134-11e5-999b-19aa381536da.gif)

**Comment by ijanos** [comment]
Awesome! This is how I imagined it should work.
