### ISSUE TITLE
Tab activation when replacing pending tabs isn't correct

### ISSUE THREAD

**Issue by BinaryMuse** [atom/tabs#278]
1. Open a tab in pending state
2. Open another file by double-clicking tree view or using fuzzy-finder (anything that calls `atom.workspace.open(...)`)

![pending-tab-change-bug](https://cloud.githubusercontent.com/assets/189606/13514366/0ecfc8a6-e15d-11e5-9e98-ab97f9750369.gif)

Atom 1.7.0-dev-19623b3 (Safe Mode)

/cc @kuychaco

**Comment by 50Wliu** [comment]
I've noticed this as well.
