### ISSUE TITLE
Uncaught Error: Pane has been destroyed (moveItemBetweenPanes)

### ISSUE THREAD

**Issue by Arcanemagus** [atom/tabs#279]
Steps to reproduce:

1. Open a file in preview mode (single click)
2. Split a file right (opens in "regular" mode)
3. Single click on a third file, this should open in preview mode in the right pane
4. Attempt to drag the newest preview mode tab over to the left side

**Atom Version**: 1.6.0-beta7
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.91.1

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\pane.js:687

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\pane.js:687:15)
    at atom-tabs.TabBarView.moveItemBetweenPanes (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:669:23)
    at atom-tabs.TabBarView.onDrop (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:537:23)
```

### Commands

```
     -2:55.1.0 project-find:show (atom-text-editor.editor.is-focused)
  2x -2:53.8.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
  6x -2:50.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:44.3.0 find-and-replace:focus-previous (atom-text-editor.editor.mini.is-focused)
     -2:34.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:11 tree-view:open-selected-entry-right (span.name.icon.icon-file-text)
```

**Comment by kuychaco** [comment]
Thanks! This is fixed on master and will be in the next release.

**Comment by lukasoppermann** [comment]
Is this already out? I am getting the same error when trying to split a pane in any direction.

**Comment by kuychaco** [comment]
@lukasoppermann yes it's out. I tested the repro steps above on the latest stable version (1.7.3) and got no errors. If you haven't already, try updating and see if you still get the error. If you're still seeing it, please post detailed steps to reproduce it.

**Comment by lukasoppermann** [comment]
The arrow only occurs when you follow those steps:

1. Open a Markdown file
2. Toggle preview (opens new tab)
3. Close all tabs but NOT the preview (DO close the markdown file)
4. Open new files
5. Try to now split the markdown file off

**Comment by kuychaco** [comment]
Great, thanks for the steps. I was able to reproduce it and opened a new issue #320

**Comment by lukasoppermann** [comment]
@kuychaco thanks! 👍

**Comment by Arcanemagus** [comment]
Btw, just for consistency's sake this bug shouldn't have the `needs-reproduction` label :stuck_out_tongue:.
