### ISSUE TITLE
Preview tabs should be on by default

### ISSUE THREAD

**Issue by samuelpismel** [atom/tabs#282]
Why this isn't on by default?

**Comment by 50Wliu** [comment]
It is starting in the 1.6.0 betas.

**Comment by dragonxlwang** [comment]
@50Wliu , i'm at atom 1.6.0 and now it disable toggle this option anymore. However, I want to revert to back single-click open. How? Thanks!

**Comment by mnquintana** [comment]
@dragonxlwang Take a look at the blog post about Atom 1.6: http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html

**Comment by dragonxlwang** [comment]
thx!
