### ISSUE TITLE
Tooltip Hide!

### ISSUE THREAD

**Issue by DHidee66** [atom/tabs#283]
Hi,

Is there a way to remove the tooltip showing in the tabs?
Or the animation of the close button / define a working set plus button / tooltip over strings etc.
Maybe an option in the settings to turn off all the animations would be helpful.

Thank You!

**Comment by lee-dohm** [comment]
To my understanding, the animations you see are part of the theme. To remove them you can change your theme. To my recollection, the [atom-dark-ui theme](https://github.com/atom/atom-dark-ui) has much fewer to no animations.

As far as the tooltips go, that's a harder problem. There are a lot of tooltips spread throughout the application, not just in the tabs package. If you want them all disabled, this should probably be reopened on the https://github.com/atom/atom repository. Is that what you're looking for?

**Comment by DHidee66** [comment]
@lee-dohm Yeah that's probably the right thing to do. Thanks :)
