### ISSUE TITLE
double click doesn' t open preview tabs permanently

### ISSUE THREAD

**Issue by snrbrnjna** [atom/tabs#285]
When double clicking a file in the tree view the file is opened in preview mode - not as mentioned next to the preview tab checkbox permanently.

MacOS 10.10
Atom 1.5.4
atom/tabs 0.88.0

**Comment by mnquintana** [comment]
This has been added in the 1.6 betas – it'll be out in the next stable release of Atom, or you can try it out now in the [Atom beta](https://atom.io/beta).
