### ISSUE TITLE
New tab behavior not working

### ISSUE THREAD

**Issue by brado** [atom/tabs#287]
I have installed both Atom 1.6.0 and 1.7 Beta and am having the same behavior on both. I have tested this on a new MacBook Pro running OS X El Capitan 10.11.3. 

- If my editor pane is empty, (no files / tabs open) and I single-click on a file in the left-hand tree-navigator pane, then that file is opened in a new tab.
- If there is a file open in a tab in the editor pane, and I single-click on a file in the left-hand tree-navigator pane, it does not open a new tab, it replaces the file in the existing tab.
- If there is a file open in a tab in the editor pane, in the left-hand tree-navigator, if I double-click that file in the left-hand tree-navigator, and then single-click a different file, it will then open that different file in a new tab. But that is the only way I have found to open a file in a new tab. 

This is bizarre, and different from my previous installation of Atom on a different Mac, which opened a new tab every time I clicked on a file in the left-hand tree-navigator pane. I clearly do not want files that I am editing in tabs removed / replaced while I am working on them if I want to view another file and click on it. 

What is going on -- is this a new configuration issue (bug or feature)? How can I fix this so that any time I single-click on a file in the left-hand tree-navigator it will open the file in a new tab? 

Thanks.

**Comment by thomasjo** [comment]
This is by design; what you are seeing is the *Pending Pane Items* feature.
Please see http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html for more details, including how to disable the new behavior.

**Comment by brado** [comment]
@thomasjo thanks a million....now that I understand what is supposed to happen, that's actually a pretty neat feature. I think my understanding of this was convoluted by something else, and I suppose I'll mention this in the off-chance this might be an issue (though hopefully it isn't). I had happened to install both Atom 1.6.0 and then 1.7-beta because I'm running on OS X and was getting bitten by the PATH / environment launching problem. I caught something on the web site that said that 1.6.0 and 1.7-beta could run independently alongside each other just fine.

I suppose depending on your perspective, they do -- they coexist in the /Applications folder and can each be launched independently. What I did not expect is that 1.6.0 and 1.7-beta are using the same preferences file apparently, so changing config for 1.7-beta changes 1.6.0 and vice versa, even though these apps appear like they are separate apps. I was changing config for one wanting to compare differences, but getting the same behavior on both, even though I had only changed one version's preferences. If that's expected, then I guess I'm the wiser. 

Anyway, thanks for your help

**Comment by thomasjo** [comment]
They do share the same preferences. You can sort of get the behavior you expected by e.g. making an alias that sets the `ATOM_HOME` environment variable before launching Atom;
```bash
alias atom-beta="ATOM_HOME=~/.atom-beta atom-beta"
```

**Comment by brado** [comment]
Thanks @thomasjo ....I appreciate it!
