### ISSUE TITLE
Preview Tabs option is missing

### ISSUE THREAD

**Issue by kevinlewis13** [atom/tabs#288]
The "Use Preview Tabs" option is missing on my fresh install of Atom.

I recently switched to a new laptop, and after installing Atom, this incredibly useful feature isn't showing anymore. I've looked at my old laptop, and the package versions are the same.

**Comment by kevinlewis13** [comment]
Although, on further investigation, the behavior is present. Did this option move to a different package?

**Comment by mnquintana** [comment]
Take a look at the [Atom blog post for 1.6.0](http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html) – this behavior has been renamed "Pending Pane Items" and has been moved to Core Settings and enabled by default.

![image](https://cloud.githubusercontent.com/assets/823545/13963481/c71afb82-f022-11e5-9a95-993dd821fca9.png)

Sorry for the confusion here!
