### ISSUE TITLE
How do I disable preview tabs?

### ISSUE THREAD

**Issue by alex-ngv** [atom/tabs#291]
I don't have the option that's listed on this page, how do I disable preview tabs?

https://atom.io/packages/sublime-tabs

**Comment by CaptainMan** [comment]
Are you looking at the settings page for Atom (`Ctrl` + `,`) or the settings page for this package (Click `Packages` on the left bar when you do `Ctrl` + `,`, then search for the package called `tabs`, then check the settings of *that*.)

**Comment by mnquintana** [comment]
https://atom.io/packages/sublime-tabs was a community package that provided this feature before it was included in core. See https://github.com/atom/atom/issues/11243#issuecomment-199959295 for more information about disabling Pending Pane Items (formerly known as Preview Tabs).
