### ISSUE TITLE
Preview tabs do not work

### ISSUE THREAD

**Issue by derrickshowers** [atom/tabs#292]
Preview tabs have seem to stop working. See animated gif.

![tabs](https://cloud.githubusercontent.com/assets/1372292/14002096/dccd099a-f106-11e5-8850-1ae40df99f98.gif)

Atom 1.6.0, tabs 0.91.3

**Comment by mattstyles** [comment]
Odd, I have the same versions as you and the preview tab is working as intended.

However, I dont get the preview tabs button, which seems to be on because its using the preview tab, which is doubly annoying as I dont want it to! ha ha.

**Comment by mnquintana** [comment]
@derrickshowers Can you reproduce this after quitting Atom completely and reopening it in safe mode? (`atom --safe`) If so, can you post your config?

@mattstyles See https://github.com/atom/atom/issues/11243#issuecomment-199959295

**Comment by arctwelve** [comment]
I don't have the option for preview tabs unless I add it to the config. Either way, clicking once on an item in the menu tree opens the item with an italicized name in the tab. Behavior is identical as if I had double-clicked. What is it supposed to do when it's functioning normally?

**Comment by derrickshowers** [comment]
@mnquintana Didn't know about safe mode, but that helped me narrow down the issue. Root issue was [this package](https://github.com/mark-hahn/tab-smart-sort). Opened [an issue](https://github.com/mark-hahn/tab-smart-sort/issues/7) on that repo.
