### ISSUE TITLE
Preview tabs request: setting to persist tab after fuzzy find

### ISSUE THREAD

**Issue by jmeas** [atom/tabs#295]
Hi there! I wasn't sure if this issue belonged in the fuzzy-find repo, or here, or maybe the main Atom repository. Point me in the right direction if I'm in the wrong place.

I **love** the preview tabs feature. It's one of the main reasons I was converted from a ST user to an Atom user.

One bit of functionality that wasn't brought over from ST is the interop between fuzzy search and preview tabs. In Sublime, if you fuzzy find a file, it's not loaded in a preview state. This allows you to fuzzy search and find a large number of files.

This is usually how I get started on working on a feature (rather than digging through the file tree to find each individual file related to the feature), so it adds an extra step when I'm getting set up in Atom. I need to fuzzy find the file, then right click it to open it in the tree view, and then double click it there.

I'd love it if either:

1. fuzzy find persisted tabs always
2. a setting was added to toggle this feature

Does anyone else feel similarly? I'd normally be happy to implement this myself, but I don't know CoffeeScript and don't think I've got time to learn it for this feature (unless it's a quick fix).

**Comment by 50Wliu** [comment]
Hi @jmeas, it sounds like you're running on an outdated version of Atom.  As of 1.6.0 files opened from the fuzzy finder *should* be permanent.  If that's not the case, then can you please open an issue on fuzzy-finder?  Thanks.

**Comment by jmeas** [comment]
Ahh! I've updated, and it's fixed. Thanks @50Wliu . ...I could have sworn I had updated Atom in the past few days.
