### ISSUE TITLE
Out of order with ctrl+tab traversal

### ISSUE THREAD

**Issue by smaili** [atom/tabs#299]
If you manually reorder the tags, and then attempt to iterate through them using the `ctrl` + `tab` shortcut, the order does not match the newly reordered tabs.

This is running version 1.6.2 on Mac OS.

**Comment by 50Wliu** [comment]
This is most likely because tab switching using ctrl + tab is now most-recently-used based rather than sequential.

**Comment by arnellebalane** [comment]
@50Wliu is there a way (like a setting somewhere) to switch back to the old tab-switching behavior rather than most-recently-used? I checked the settings page and I couldn't find any, and I personally prefer the old tab switching behavior over the most-recently-used one.

**Comment by smaili** [comment]
@arnellebalane see here - https://github.com/atom/atom/issues/5344

**Comment by arnellebalane** [comment]
@smaili omg thank you, im doing the `keymap.cson` workaround and it's good enough for me for now. But I think it's still better though to have a setting to toggle between the two tab-traversal modes. But I'm okay that I got the old behavior back so thanks again :smile:
