### ISSUE TITLE
[Feature] sort tabs alphabetically

### ISSUE THREAD

**Issue by pke** [atom/tabs#303]
Current order of tabs is depending on the order you open files.
It would be a nice options to have the tabs be sorted alphabetically.

**Comment by anderoonies** [comment]
right now there are two options for tab ordering, with/without the `addNewTabsAtEnd` config.
adding a third option would probably precipitate abstracting out ordering so there's not just a big `switch` statement
not sure if this or other future, possible tab orderings are in-demand enough to make this worthwhile

**Comment by a7madgamal** [comment]
you can check this out, not perfect but not bad also :)
https://atom.io/packages/tab-smart-sort

**Comment by pke** [comment]
Using VSCode for a while now ;)
