### ISSUE TITLE
Tabs randomly changing

### ISSUE THREAD

**Issue by artur99** [atom/tabs#305]
The tabs are randomly switched when I press `Ctrl+Tab` or `Ctrl+Shift+Tab`
OS: Windows 10
Tabs: 0.92.0

This bug seemed to appear a few days ago, no idea why... Demo image:
![](http://i.imgur.com/VHY8QhI.gif)

(just a screen recording where I've pressed `Ctrl+Tab` 4 times in a row, but the tabs switched randomly)

**Comment by joefitzgerald** [comment]
This is called Most Recently Used (MRU) tab behavior: http://blog.atom.io/2016/04/12/atom-1-7-and-1-8-beta.html provides instructions on how to restore the old behavior if you wish.
