### ISSUE TITLE
Preview Tabs

### ISSUE THREAD

**Issue by rtoshiro** [atom/tabs#316]
Sorry, but I've search about "Preview Tabs" option but I can't find it in my tabs settings.
I've already updated everything. How can I disable Preview Tabs and open files with one single click as it was before?
I works when I check "Allow Pending Pane Items" in Atom settings, but it replaces the current tab with the file I've selected. I would like to open new files with one single click as it was in the past.
Thank very much.

**Comment by 50Wliu** [comment]
You can install the [single-click-open](https://atom.io/packages/single-click-open) package.

The "Preview Tabs" option was replaced by the pending pane items option.
