### ISSUE TITLE
Moving tabs between panes with Add New Tabs At End

### ISSUE THREAD

**Issue by Ben3eeE** [atom/tabs#329]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description
If you move a tab using mouse drag and drop from one pane to another it will be moved to the end of the tab bar if you have the "Add New Tabs At End" configuration option enabled.

### Steps to Reproduce

1. Open Atom in safe mode.
2. Ensure you have the "Add New Tabs At End" configuration option set to true. This is found in the configuration options for the Tabs package.
3. Split the Atom window to two different panes.
4. Open a bunch of tabs in each pane.
5. Drag and drop a tab from one pane to the other, the moved tab gets added in the end rather than where it was dropped.

![add tabs at end move to other pane](https://cloud.githubusercontent.com/assets/1058982/15507081/645f32fe-21ca-11e6-9b92-d4bc5077a49f.gif)

**Expected behavior:** Tab to be moved where it was dropped and not to the end. Technically this is a new tab in that pane but it is also dropped in a specific location which I think should take precedence.

**Actual behavior:** Tab is moved to the end when it is dropped.

**Introduced by:** https://github.com/atom/tabs/pull/273

**Partially fixed by:** https://github.com/atom/tabs/pull/276 This only fixed it for tabs moved within the same pane.

cc @anderoonies

#### atom --version

```
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

#### apm --version

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.1.windows.1
visual studio
```

Windows 10

**Comment by anderoonies** [comment]
ah, the feature that made a thousand bugs
i have an easy fix for this, making sure tests are exhaustive then pushing it up.
@Ben3eeE thank you for finding this bug, god knows i wouldn't have

**Comment by anderoonies** [comment]
PR is up, thanks again and sorry for any trouble
