### ISSUE TITLE
Always Open File in New Tab

### ISSUE THREAD

**Issue by davidbarratt** [atom/tabs#33]
I'm not sure if this issue should go here or on Tree.

Basically when you open a file, it sometimes opens in new tab and sometimes opens in a new window. The behavior is rather unexpected. I think it would have been more expected if it worked like a browser (always opens in a new tab unless explicitly told to open in a new window). Or it might be nice to have options to fit peoples needs.

I understand that the reason why it doesn't always open in a new tab is because the context is different (the tree structure). However, the tree should really be on a per-tab basis I would think, rather than a per-window basis anyways.

Ideally, the tree should always show the current tab's position in the tree of the file system (maybe the next highest .git directory would be the root of that tab's tree).

Thanks!

**Comment by kevinsawicki** [comment]
Now that multi folder projects are supported, you can open files from any folder in the current window and manage multiple top level folders in one window, closing this out.

http://blog.atom.io/2015/04/15/multi-folder-projects.html

**Comment by maiksd** [comment]
I find that this isn't fully addressed by the multi-folder feature. I usually don't care about the tree and hide it, and I'm just opening files from different locations, and I always want them to open in tabs, but often they open in separate windows, and I then have to shuffle the tabs around.
