### ISSUE TITLE
Stop override the default `delay` values when adding tooltip

### ISSUE THREAD

**Issue by Greenek** [atom/tabs#333]
Hello! 

I want to make tooltips pop up faster. I have a project that contains files with similar names, but in different directories. When I have opened simultaneously a few of them, I cannot see which is which until I click or wait for a tooltip, but it takes up a second. Atom does not support changing the default value of delay in settings, but it can be overwritten by adding

````coffeescript
atom.tooltips.defaults.delay.show = 100
````

to the `init.coffee` file. Unfortunately, it does not affect the delay of the tabs tooltips, because plugin [adds them overwriting the default `delay` value](https://github.com/atom/tabs/blob/b31ae3d293fb2dccd140e69cf91953ce85e286b5/lib/tab-view.coffee#L155). As long as [these values are identical](https://github.com/atom/atom/blob/f48069c5f848b5ae624b110a1df7800e919eb142/src/tooltip-manager.coffee#L48) setting them is redundant.

Can we remove it?

**Comment by Ben3eeE** [comment]
@Greenek Thought you would be interested in https://github.com/atom/atom/pull/13095

**Comment by Greenek** [comment]
Awesome! Thank you :)
