### ISSUE TITLE
Tabs squeezed to a small space

### ISSUE THREAD

**Issue by Jiia** [atom/tabs#342]
At some point yesterday my tabs became very small, not utilizing the space properly. Now the tabs are so small that if the file name is short, I often accidentally press the close button when trying to select the tab. I have no idea how to fix this issue. I'm not sure if it's a new feature or a bug.

[Screenshot](http://i.imgur.com/KcN3z8x.png)

**Comment by 50Wliu** [comment]
@Jiia see atom/one-dark-ui#139.
