### ISSUE TITLE
Small tabs after upgrade to atom 1.8.0 (OS X)

### ISSUE THREAD

**Issue by isuraed** [atom/tabs#343]
This morning atom upgraded from 1.7.4 to 1.80 and I noticed the tabs are very small. The tabs only become "normal" size after I maximize the window. This is on OS X El Capitan with a macbook pro retina.

<img width="1104" alt="screen shot 2016-06-09 at 8 43 14 am" src="https://cloud.githubusercontent.com/assets/4210603/15936006/416afef8-2e1e-11e6-9449-256519038a6f.png">

**Comment by 50Wliu** [comment]
Please see [The tabs got shorter in v1.8.0, what happened? How do I go back?](https://discuss.atom.io/t/the-tabs-got-shorter-in-v1-8-0-what-happened-how-do-i-go-back/29791) on Discuss.
