### ISSUE TITLE
inconsistent tab size

### ISSUE THREAD

**Issue by wendy0402** [atom/tabs#347]
Hi Guys,
I recently have an issue with the tab, as you can see
![screen shot 2016-06-15 at 11 51 04 am](https://cloud.githubusercontent.com/assets/4647969/16068530/c772cd6a-32f0-11e6-8800-f9550de5435d.png)
![screen shot 2016-06-15 at 11 50 33 am](https://cloud.githubusercontent.com/assets/4647969/16068531/cef2a448-32f0-11e6-96fb-e503ca08a4e8.png)

the current tab size suddenly become bigger than the others. so when I need to switch tab by click it, suddenly it become bigger and kinda suprise me everytime. Navigation is really hard since with several tab opened, I need to think back again which I need to open. How about we switch it back to the old style
![screen shot 2016-06-15 at 12 06 38 pm](https://cloud.githubusercontent.com/assets/4647969/16068649/bd1c01b4-32f1-11e6-9dfb-5184e59d5773.png)

Like any other text editor
![screen shot 2016-06-15 at 12 00 00 pm](https://cloud.githubusercontent.com/assets/4647969/16068593/49d30252-32f1-11e6-816c-54d6a021bb3a.png)
![screen shot 2016-06-15 at 12 04 43 pm](https://cloud.githubusercontent.com/assets/4647969/16068607/660da206-32f1-11e6-8098-db3c329f0040.png)

**Comment by simurai** [comment]
@wendy0402 There was a recent change, here how you can [make the tabs even again](https://discuss.atom.io/t/the-tabs-got-shorter-in-v1-8-0-what-happened-how-do-i-go-back/29791).

But not sure if that's the problem since in your case the active tab expands.

1. Does it also happen in safe mode `atom . --safe`?
2. Do you mind pasting your config file?

**Comment by wendy0402** [comment]
ah, you are correct. my config for tab sizing is auto. I use atom v 1.8.0, and using `atom . --safe` make the tabs even. thanks a lot!

**Comment by simurai** [comment]
What about without using `atom . --safe` and `Even`? `atom . --safe` doesn't load any packages, so it's just useful for testing.

**Comment by wendy0402** [comment]
without them, my config is auto

**Comment by simurai** [comment]
ok, if I understood it right, changing the setting solved the problem. I'll close this then.
