### ISSUE TITLE
Tab size too short, miss clicks are frequently.

### ISSUE THREAD

**Issue by chmercesmoreira** [atom/tabs#348]
What I want to request is a minimum fixed size for the tabs because apparently the tab size is related with the file name, and in some cases the file name is too short, causing this:
![atom](https://cloud.githubusercontent.com/assets/20016536/16172443/ea5cace4-355f-11e6-8db1-33a104e348f9.png)
Note the size of the tab "gad.h", frequently when I try to switch to that tab I close it accidentally.

**Comment by thomasjo** [comment]
I'm closing this as a duplicate of https://github.com/atom/atom/issues/11448. Feel free to post your image, etc. there.

**Comment by Ben3eeE** [comment]
@chmercesmoreira You can set the tab sizing to even to make sure the tabs are evenly sized regardless of filename length I believe. This does not fix the problem that the close button is too big but it gives a bigger area to click for shorter filename tabs.
https://discuss.atom.io/t/the-tabs-got-shorter-in-v1-8-0-what-happened-how-do-i-go-back/29791

**Comment by swelther** [comment]
Thank you for the link @Ben3eeE. Got annoyed from this but did not search for the tab options in the themes 😀 👍
