### ISSUE TITLE
Adding tabs "stretches" other views in 1.9.0-beta0

### ISSUE THREAD

**Issue by AEgan** [atom/tabs#350]
I'm not sure of the best way to phrase the subject. I've left a gif of the problem below. When you open enough tabs so that scrolling becomes enabled, other views extend beyond the visible window. I first noticed this with the minimap package, but I was able to reproduce with find and replace in safe mode, and with the tree view set to display on the right. I removed all code from my stylesheet and init script as well. I also noticed that I am unable to scroll, but saw #345. Not sure if these are related or not so I figured I'd open an issue.

Atom version 1.9.0-beta0
Tabs version 0.98.0

Here's the gif. As I add new tabs, focus on the find and replace options on the bottom right, which are pushed off screen.

![tabscrollingbehavior](https://cloud.githubusercontent.com/assets/3501927/16247508/0d076d22-37d8-11e6-963b-c68a399e46f8.gif)

**Comment by 50Wliu** [comment]
This has already been fixed and will be out in 1.9.0-beta1 when that gets released.
