### ISSUE TITLE
Tab width

### ISSUE THREAD

**Issue by sharifzadesina** [atom/tabs#351]
Increase default tab width, This is default tab width:
![2016-06-22_02-58-27](https://cloud.githubusercontent.com/assets/15300551/16248579/469ec1e6-3825-11e6-8c49-b5e0b4f62d9e.png)

Also dynamic tab width doesn't work for me.

atom 1.8 windows 8.1

**Comment by mnquintana** [comment]
It looks like your window is on the small side – One Light UI is responsive by default, so the default tab width will change depending on the side of the window. If you want to disable this, you can go to Preferences > Themes > one-light-ui > Layout Mode and change that to Spacious. Hope that helps!

**Comment by sharifzadesina** [comment]
Spacious mode doesn't help.
In that page, Changing "Tab Sizing" value to "Even" solved my problem.
But a question, Why this not occur to other versions of atom? (e.g. 1.7)
Where is the problem from? my laptop's resolution is 1366x768

**Comment by 50Wliu** [comment]
> But a question, Why this had not occurred to other versions of atom? (e.g. 1.7)

The Tab Sizing option is new in 1.8.  Any resolution below 1280x800 will default to min-width tabs.
