### ISSUE TITLE
Add setting to allow switching between tabs with Ctrl Tab/Ctrl Shift Tab following the visual order

### ISSUE THREAD

**Issue by Keavon** [atom/tabs#353]
For me, it's really annoying how <kbd>Ctrl</kbd><kbd>Tab</kbd> and <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>Tab</kbd> don't switch directly to the left and right, and instead switch based on previous visitation. Please add an option to the package settings page to allow this to work on a visual left/right basis.

**Comment by mnquintana** [comment]
This looks like a duplicate of https://github.com/atom/atom/issues/11035 – feel free to subscribe there for updates.
