### ISSUE TITLE
Change tabs to always fit within window size

### ISSUE THREAD

**Issue by pydolan** [atom/tabs#357]
I vaguely remember this being the standard behavior of Atom, at least until a recent update: similar to how tabs are handled in browsers like Chrome, the tabs should not have a horizontal scroll and should instead change size (thus hiding more of the filename) as the tab pane fills up.

If I am indeed remembering the past behavior of Atom, why did this change? Can we add an setting to enable the old method?

**Comment by simurai** [comment]
@pydolan Are you using the One UI theme? There has been a recent change to switch automatically based on the window size. If you prefer the previous behavior, you can change it back to "Even", see: https://discuss.atom.io/t/the-tabs-got-shorter-in-v1-8-0-what-happened-how-do-i-go-back/29791

**Comment by pydolan** [comment]
Thanks @simurai!  That's exactly what I was looking for.
