### ISSUE TITLE
Cursor position loses focus when changing tabs with keyboard

### ISSUE THREAD

**Issue by Perrishnikov** [atom/tabs#358]
Whilst traversing the tabs in my project when using the keyboard (control-tab or command-alt-arrow). The focus changes from the buffer/editor (whatever its called) and heads over to the tree view and the file that I tabbed into.

Behavior is fine if I use the mouse to change tabs, but as you can imagine, its annoying to constantly need to mouse to get the cursor back into the document. 

OSX, Atom 1.8.0

**Comment by 50Wliu** [comment]
@Perrishnikov Does this happen in safe mode (`atom --safe`)?

**Comment by Perrishnikov** [comment]
@50Wliu  Yes, the problem persists.

**Comment by mnquintana** [comment]
I can only reproduce this if the Tree View is focused before switching tabs with the keyboard shortcuts. Is that also the case for you @Perrishnikov?

**Comment by Ben3eeE** [comment]
Do you have both Auto Reveal and Focus on Reveal in the tree-view package settings on? Then this is a duplicate of https://github.com/atom/tree-view/issues/858.

**Comment by Perrishnikov** [comment]
@Ben3eeE Thanks for the suggestion. By unchecking the Focus On Reveal option, the behavior is as I expect it to be. I had no idea this was a Tree View 'feature' and not a tabs bug which is where I had been searching for similar issues.

**Comment by Ben3eeE** [comment]
Closing as a duplicate of https://github.com/atom/tree-view/issues/858.
