### ISSUE TITLE
Lots of open tabs decrease performance and crash on tab close.

### ISSUE THREAD

**Issue by emainier** [atom/tabs#36]
The performance decrease when a lot of tabs are open. Sometime the editor crash when I try to close tabs : a window is asking if I want to wait or to close the editor.

If I choose "close", when I try to reopen the same folder, all my tabs are open, so the editor crash again as soon as I try to close some tabs.

To reproduce: 
-open a folder
-open a lot of files in editor tabs (about 50)
-right click on a tab and choose "Close Other Tabs"

--> If you have the message "Editor is not responding" and choose to close it, if you try to reopen the same folder, all your tabs will be reopen on launch causing a really slow opening and a new crash as soon as you try to close the open tabs.

**Comment by benogle** [comment]
Closing in favor of atom/atom#2287. This likely has nothing to do with tabs.
