### ISSUE TITLE
Tooltip gets stuck if visible when closing the pane

### ISSUE THREAD

**Issue by Ben3eeE** [atom/tabs#362]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
The tooltip shown when hovering over a tab does not close if it was visible when closing the pane.
Same as https://github.com/atom/tabs/issues/7 only this happens when closing the pane and not the tab.

### Steps to Reproduce

1. Open Atom in safe mode with a multi pane layout.
2. Hover over one of the open tabs and wait for the tooltip to appear.
3. Right click and choose close pane from the menu.

![tooltip close pane](https://cloud.githubusercontent.com/assets/1058982/17511390/f26a8bd6-5e22-11e6-8fb4-60f484ac81df.gif)

I have also seen this when closing the pane from the context menu before the tooltip is visible, it then gets stuck in the top left corner.

**Expected behavior:** Tooltip to close because tab gets closed.

**Actual behavior:** Tooltip does not close and is always visible.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Windows 7.

```
atom --version
Atom    : 1.9.7
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

```
apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 1.9.2.msysgit.0
visual studio
```

**Comment by 50Wliu** [comment]
Cannot reproduce on Atom 1.11.0-dev-ac75135, Windows 10 x64.  Maybe this is another Classic mode bug?

**Comment by Ben3eeE** [comment]
Same issue on Windows 10 Atom 1.10-beta4 and so not classic mode bug. I will fool around with settings to see if I can figure out if something specific causes this.

**Comment by Ben3eeE** [comment]
The tooltip disappears if I resize the Atom window or toggle the menu bar with <kbd>alt</kbd>. Stuck otherwise.

**Comment by Ben3eeE** [comment]
I can't find any specific setting or something causes this, it happens every time I close the pane using the tabs context menu, but not if the pane gets closed in another way for example by closing the last tab with remove empty panes on.

All I found when testing is that other panes, depending on layout, can resize when a pane is closed. They go back to original size when the Atom window gets resized.

![close pane moves pane](https://cloud.githubusercontent.com/assets/1058982/17582204/9d347616-5faa-11e6-883a-3d3cb486b6ef.gif)

**Comment by 50Wliu** [comment]
Can now confirm on Atom 1.12.0-dev-d79690e.

**Comment by 50Wliu** [comment]
This is because the `.destroy()` function of each tab isn't called when the pane is closed.
