### ISSUE TITLE
Feature Request: Key binding to keep previewed tab open

### ISSUE THREAD

**Issue by cabloo** [atom/tabs#369]
When on a preview tab, there should be a key binding that changes the status of the current tab from previewing to staying open.

This would be useful when coming off of the search page (where a double click opens the tab in preview mode).

**Comment by cabloo** [comment]
Just discovered that saving the file (even with no changes) forces it to stay open. It would be nice for this to be mentioned on the settings page somewhere, ideally in the keybindings area.

**Comment by mnquintana** [comment]
We're trying to avoid adding more bundled keybindings, to keep them available for community package authors. You can add a [custom keybinding](http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings) of your own, though!

Pending pane items (formerly known as Preview Tabs) are documented in the [Flight Manual](http://flight-manual.atom.io/using-atom/sections/pending-pane-items/).

Hope that helps!
