### ISSUE TITLE
auto-indent frequently does the wrong thing

### ISSUE THREAD

**Issue by jdhenckel** [atom/tabs#370]
for example try to auto-indent this code

                if (response.data && response.data.ExceptionMessage 
                    && response.data.ExceptionMessage.startsWith("Missing userid")) {
                    $scope.showLogon = true;
                }
                else {
                    alert(JSON.stringify(response));                        
                }
 
It will indent the first $scope too far, because the "if" is broken over two lines.

**Comment by mnquintana** [comment]
This is not the tabs you're looking for 😄  – take a look at these existing issues: https://github.com/atom/atom/issues?q=is%3Aopen+is%3Aissue+label%3Aauto-indent
