### ISSUE TITLE
Tabs missing on arch

### ISSUE THREAD

**Issue by ForsakenHarmony** [atom/tabs#381]
Tabs are missing and text in the menu bar as well, but that one's because of my xfce theme

![alt text](http://i.imgur.com/3FYKoby.png)

**Comment by Ben3eeE** [comment]
Please provide the output of `atom --version` and `apm --version`.
Does this happen in safe mode `atom --safe`?

**Comment by ForsakenHarmony** [comment]
```

**Comment by ForsakenHarmony** [comment]
yes, it does also happen in safe mode

**Comment by 50Wliu** [comment]
> Electron: 1.4.1

You are using an unsupported Atom distribution.  Please uninstall it and reinstall Atom from https://atom.io.

See https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md for more information.

**Comment by ForsakenHarmony** [comment]
oh, right, sorry
