### ISSUE TITLE
Jump to tabs with 'ctrl+1-9'

### ISSUE THREAD

**Issue by MoritzKn** [atom/tabs#391]
It would be nice to have the ability to jump between tabs with <kbd>ctrl-1</kbd>-<kbd>ctrl-9</kbd>. You can already find this behavior in the chrome browser, therefore I would recommend to copy this behavior.
What I would expect in detail:
<kbd>ctrl-1</kbd> jump to the first tab from the left
<kbd>ctrl-2</kbd> jump to the second tab from the left
and so on..
<kbd>ctrl-8</kbd> jump to the eighth tab from the left
<kbd>ctrl-9</kbd> jump to the last tab from the left

**Comment by Ben3eeE** [comment]
This is already available using the `pane:show-item-[number]`. The default keybind for this is <kbd>alt-[number]</kbd> on Windows and Linux and <kbd>Cmd-[number]</kbd> on macOS.

If you want to change the keybindings to <kbd>ctrl-[number]</kbd> check out the [keymaps in depth](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/) section of the flight manual or ask on the [Atom message board](https://discuss.atom.io) for help.

**Comment by MoritzKn** [comment]
@Ben3eeE great, thanks for informing me!

**Comment by Ben3eeE** [comment]
You're welcome :slightly_smiling_face:
