### ISSUE TITLE
New file only opening after reloading atom

### ISSUE THREAD

**Issue by Chais** [atom/tabs#395]
When I try creating a new file it won't appear until after I restarted Atom. I'm rather new to Atom and not at all familiar with its logging and debugging capabilities. So if there's info you need, please let me know.  
To reproduce:

1. Open Atom (empty or with open files doesn't matter for me)
1. Press `ctrl + N` and/or select `New File` from the `File` menu
    - No new tabs name `untitled`
1. Close and reopen Atom
    - Find as many new tabs as you tried to open

I'm not using the default theme, if that does matter (I feel it shouldn't)

**Comment by 50Wliu** [comment]
Is this reproducible in safe mode (`atom --safe`)?  In addition, what is the output of `atom --version`, and what OS are you using?

**Comment by Chais** [comment]
> Is this reproducible in safe mode (`atom --safe`)?

Yes.

> what is the output of `atom --version`

```
Atom    : 1.11.2
Electron: 1.4.5
Chrome  : 53.0.2785.113
Node    : 6.5.0
```

> what OS are you using?

Archlinux running kernel 4.8.6.

**Comment by isaac-nugroho** [comment]
I experience the same case, new file only opening after reloading atom, including atom --safe. I'm using arch linux with xfce4 as desktop manager.

`atom --version`

`Atom    : 1.11.2`
`Electron: 1.4.5`
`Chrome  : 53.0.2785.113`
`Node    : 6.5.0`

`uname -a`
`Linux ziggy 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux`

**Comment by 50Wliu** [comment]
> Electron: 1.4.5

Both of you are running unsupported versions of Atom.  My recommendation is to uninstall Atom and reinstall it from the official site, https://atom.io.

See https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md for more details.
