### ISSUE TITLE
Clicking a file in project pane replaces unedited file tabs

### ISSUE THREAD

**Issue by siteleas** [atom/tabs#403]
**When I click on a file in my project pane, if the file in the active tab has not been altered, the unedited file in the active tab closes and the file I just clicked on replaces it.** 

If this is a feature, there should be a way of turning that "feature" off. My workflow is such that I click on all the files I want to work on, one at a time, and then switch between them, using the tabs feature set. Sometimes I don't need to edit those files, but merely compare them, or copy content from one (unedited) file to a file I would like to edit.

Is there a way to disable this replace unedited tab replacement feature? Is there a setting I just haven't found that I need to change?

**Comment by 50Wliu** [comment]
If you double-click the file, it will become a permanent tab.

To disable this feature, go into the Settings View and uncheck the "Allow Pending Pane Items" option.

**Comment by 50Wliu** [comment]
Sure.

1. Open Atom
2. Open the Settings View (on Windows: File -> Settings, on Linux: Edit -> Preferences, on macOS: Atom -> Preferences...).  You can also open it using the Command Palette and searching for the settings view, or using the <kbd>Ctrl+,</kbd> or <kbd>Cmd+,</kbd> shortcut.
3. "Allow Pending Pane Items" should be the first option.

![allow-pending-pane-items-option](https://cloud.githubusercontent.com/assets/2766036/21583386/70f98862-d04c-11e6-9c2b-538faa125c41.png)

Hope that helps!
