### ISSUE TITLE
Show tabs in MRU order

### ISSUE THREAD

**Issue by LukaHorvat** [atom/tabs#409]
It would be great to have an option that automatically reordered tabs in MRU order. 
This would mean the current tab is always first and that ctrl-tab always switches to the tab on the right, while still keeping the reasonable MRU behavior.

**Comment by lee-dohm** [comment]
Thanks for the suggestion. This isn't something that we're planning on implementing. We are planning on implementing an MRU tab visualization that goes along with the MRU tab switching that was added a while back, but it will be separate from the normal tabs visualization.

**Comment by LukaHorvat** [comment]
Hmm, sounds good. Is there anywhere I can read about how this will look?

**Comment by Ben3eeE** [comment]
@LukaHorvat You can read about the MRU tab traversal changes in the [blog post for Atom 1.14 beta](http://blog.atom.io/2017/01/10/atom-1-13.html).
