### ISSUE TITLE
Deleting folder with open files using tree view causes tabs to remain open

### ISSUE THREAD

**Issue by adamreisnz** [atom/tabs#413]
Under OS X (but I presume other operating systems as well), when I have some files open from within a certain folder, and I then delete that folder using tree view, Atom keeps the files themselves open.

This is contrary to the functionality that it closes the relevant tab when deleting a single file with tree view.

@iolsen is this something you could look at? It seems to be something that we've missed when tackling and testing #306.

**Comment by 50Wliu** [comment]
By "remove that folder", do you mean that you have removed it as a project folder, or have you deleted the folder?

**Comment by adamreisnz** [comment]
I mean deleting it, as such:

![image](https://cloud.githubusercontent.com/assets/490562/22999347/c442189c-f43f-11e6-94e1-fb3bc2a0f9ed.png)

**Comment by iolsen** [comment]
Yeah this looks like my oversight. We'll add it to the queue.
