### ISSUE TITLE
Uncaught TypeError: this.promptToSaveItem(...).then is not a function

### ISSUE THREAD

**Issue by wilvk** [atom/tabs#456]
[Enter steps to reproduce:]

1. Atom froze
2. Kill Atom from CLI
3. Start Atom from CLI
4. Click a tab to close

Note: git items that were previously commited were showing as unsaved with a blue dot on the tab. Tabs that didn't have a blue dot could be closed correctly.

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught TypeError: this.promptToSaveItem(...).then is not a function

```
At C:\Users\willem\AppData\Local\atom\app-1.19.0-beta0\resources\app\src\pane.js:709

TypeError: this.promptToSaveItem(...).then is not a function
    at Pane.module.exports.Pane.destroyItem (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/pane.js:709:52)
    at TabBarView.module.exports.TabBarView.closeTab (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
```

### Non-Core Packages

```
ansible-snippets 0.2.0 
atom-beautify 0.29.18 
auto-reveal-in-sidebar 0.8.0 
autocomplete-python 1.8.63 
busy-signal 1.3.0 
hyperclick 0.0.40 
intentions 1.1.2 
language-ansible 0.2.1 
linter 2.1.2 
linter-bootlint 1.0.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-pycodestyle 2.0.2 
linter-pylint 2.0.1 
linter-ui-default 1.2.2 
magento-tools 0.0.3 
monokai 0.22.0 
open-recent 5.0.0 
php-debug 0.2.4 
php-hyperclick 1.2.1 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.3.0 
php-integrator-base 2.1.11 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.2 
php-integrator-refactoring 1.3.1 
php-integrator-tooltips 1.1.5 
project-manager 3.3.5 
save-session 0.15.7 
seti-icons 1.4.3 
```

**Comment by therealcybernomad** [comment]
Happened to me while trying to close a tab which was not yet saved as a file. I disabled the save-session package and it worked.

## Non-Core Packages
`atom-beautify      
atom-ternjs        
busy-signal        
file-icons         
git-control        
git-log            
highlight-selected 
intentions         
language-powershell
language-regexp    
linter             
linter-jshint      
linter-ui-default  
pretty-json        
README.md          
remote-sync        
save-session       
split-diff         
symbols-list`

**Comment by rsese** [comment]
> EDIT: save-session is deprecated.

Ahhh, thanks for the info @therealcybernomad :bow:

Looks like you have save-session installed as well @wilvk - can you confirm if you can reproduce with save-session disabled?  If not, I think we can close this.

**Comment by wilvk** [comment]
Yep, looks like save-session is the culprit:
`save-session 0.15.7 `
For others viewing this thread: all of save-session's functionality is now included in Atom by default.
Thanks @therealcybernomad @rsese

**Comment by elferink** [comment]
One thing save-session did and that is not included in Atom (and the reason I had save-session installed) is saving a session that has no project.

**Comment by cwtrex** [comment]
I have been attempting to make the switch from Notepad++ to Atom and this error is currently a deterrence.  I often have sessions created temporarily with no long term plan to be saved, but may need to open and close the application in order to continue work only to remove the session/tab later upon completion.

This bug should be set to open, not closed.  Until Atom can save temp tabs like Notepad++ reliably and/or work with save-session, "Uncaught TypeError: this.promptToSaveItem(...).then is not a function" is a very real bug.

Until then, it is an annoyance, but one has to clear the temporary tab of all characters including new lines before closing out of the tab.
