### ISSUE TITLE
Tabs ordered vertically instead of horizontally

### ISSUE THREAD

**Issue by Jierr** [atom/tabs#49]
Can you add this option? It would look like tree-view and helps if you have opened shitloads of tabs.

**Comment by vilic** [comment]
Or maybe we can narrow the padding, and use a gentle gradient instead of ellipsis for taking better use of the space. Especially when there's many tabs.

**Comment by benogle** [comment]
I am closing this as a package idea. `vertical-tabs` sounds like a good name :)
