### ISSUE TITLE
Double-clicking file in tree view opens new tab but does not focus on it

### ISSUE THREAD

**Issue by kiahouzz** [atom/tabs#532]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

Open a project
Double click on a file in the tree view

**Expected behavior:** the editor auto-focuses on the new tab to display the file contents.

**Actual behavior:** the editor opens a new tab but it is hidden behind any existing tabs or even when no other tabs are open, and you must click on the tab to view the file contents.

**Reproduces how often:** Happens 100% of the time for me

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.6
Mac Sierra 10.12.6

### Additional Information

When I open atom in safe mode this does not happen, but that doesn't allow me to solve the problem. Disabling the tabs package seems to fix the issue but it's hard to tell since there are no tabs at all when this package is disabled. There are no settings in the tabs package that appear relevant to this and changing all of them did nothing to help.

**Comment by 50Wliu** [comment]
> When I open atom in safe mode this does not happen

You can use the [package-cop](https://atom.io/packages/package-cop) package to help you figure out which community package is causing the issue.
