### ISSUE TITLE
Commands matching tab contextual menu (right-click on a tab)

### ISSUE THREAD

**Issue by douglascamata** [atom/tabs#61]
I'm missing a lot commands for the tab contextual menu actions, like "Close all", "Close unmodiffied", "Close saved", etc and I guess many other users are missing them too.

**Comment by mjrk** [comment]
+1 here, too.

**Comment by halleycarleton** [comment]
**+1** - I was surprised to find no default key binding for `close all tabs`.

**Comment by titosrevenge** [comment]
+1 Would also like the keybinding for closing all tabs without closing the window

**Comment by rubencaro** [comment]
+1. closing all tabs without closing the window a must.

**Comment by lee-dohm** [comment]
There is a command for closing all tabs. And as far as I know, there are commands for all the other items in the context menu too:

<img width="613" alt="screen shot 2015-07-12 at 8 58 36 pm" src="https://cloud.githubusercontent.com/assets/1038121/8642426/cb5605c8-28d8-11e5-9dda-b2f025e3f020.png">

Closing this as fixed. If there are specific commands that are still missing, please open a single issue for each.

**Comment by mryellow** [comment]
Debian KDE - Atom 0.2
![atom_close_menu](https://cloud.githubusercontent.com/assets/213575/8642723/f50034be-296b-11e5-82ed-422093d85993.png)

**Comment by rubencaro** [comment]
Sorry, what we meant was to be able to define keybindings for these commands. At least that's what I meant.

**Comment by lee-dohm** [comment]
You should be able to define key bindings for virtually any command in the command palette. The command name is a simple transformation from the label in the command palette. In this case:

* `tabs:close-other-tabs`
* `tabs:close-saved-tabs`
* etc

See the code here:

https://github.com/atom/tabs/blob/3b4124593b42dcdf003c0ac9a7e6c50fea34e11f/lib/tab-bar-view.coffee#L17-L23

**Comment by rubencaro** [comment]
Nice!  Thanks!

**Comment by mryellow** [comment]
Your competition all have a "Close All Tabs" button on the file menu. This is an expected paradigm. Missing this button leaves new users not able to find basic functionality.
