### ISSUE TITLE
Tooltip not rendered correctly with long filepaths

### ISSUE THREAD

**Issue by fbrundu** [atom/tabs#66]
Hi,
I found this problem on Atom v0.108.0, Ubuntu 14.04

![atom](https://cloud.githubusercontent.com/assets/697622/3485126/90a10b72-03c6-11e4-9bf9-4d2652dd6583.png)

When the path is too long, the arrow of the tooltip is far away from the tooltip.
I got no errors on developer tools.

Thanks

**Comment by kevinsawicki** [comment]
There is a core issue for this now and it will be fixed there, this package just uses the core `atom.tooltips` API which is where this bug is.

https://github.com/atom/atom/issues/5009
