### ISSUE TITLE
tab path tooltip arrow offset

### ISSUE THREAD

**Issue by rakkarage** [atom/tabs#86]
![1](https://cloud.githubusercontent.com/assets/962340/4600465/0b437936-50d5-11e4-803a-68afae7550d4.png)

on windows
seems to happen for all paths
seems to be recent?

nitpicky i know but might as well report it :)

thanks

**Comment by kevinsawicki** [comment]
There is a core issue for this now and it will be fixed there, this package just uses the core `atom.tooltips` API which is where this bug is.

https://github.com/atom/atom/issues/5009
